### ISSUE TITLE
Inconsistent tokenization of "Mr." in word_tokenizer

### ISSUE THREAD

**Issue by lowdanie** [nltk/nltk#1763] opened 2017-06-30 22:34 UTC
I noticed inconsistent behavior with the nltk.word_tokenize method. Specifically, sometimes the string "Mr." gets tokenized as one token, but in other cases it is split into two tokens: ['Mr', '.']. The same holds for the string 'Ms.'.

Here is an example:

```
>>> nltk.word_tokenize('Hello Mr. Rob')
['Hello', 'Mr', '.' 'Rob']
>>> nltk.word_tokenize('Hello Mr. Dan')
['Hello', 'Mr.', 'Dan']
```

I am using nltk version 3.2.2

**Comment by alvations** [comment] 2017-07-06 02:45
@lowdanie, This is caused by the statistically trained `PunktSentenceTokenizer` that splits the sentence before performing word tokenization. 

To avoid any sentence splitting,  please use the `preserve_line=True` parameter:

```python
>>> from nltk import word_tokenize

>>> word_tokenize('Hello Mr. Rob')
['Hello', 'Mr', '.', 'Rob']
>>> word_tokenize('Hello Mr. Dan')
['Hello', 'Mr.', 'Dan']

>>> word_tokenize('Hello Mr. Rob', preserve_line=True)
['Hello', 'Mr.', 'Rob']
>>> word_tokenize('Hello Mr. Dan', preserve_line=True)
['Hello', 'Mr.', 'Dan']
```

You might need to upgrade your NLTK version to get the `perserve_line` option:

```
pip install -U nltk
```

**Comment by alvations** [comment] 2017-07-12 03:52
@lowdanie, did the previous comment help to resolve the issue? Or are you still facing the same issue with the abbreviations tokenization?

**Comment by lowdanie** [comment] 2017-07-12 05:26
Thanks a lot for alerting me to the preserve_line option. I downloaded version 3.2.4 and it seems to work. However, the documents that I am parsing have multiple sentences, so I would not necessarily want to disable sentence splitting. 

Since the tokenizer is statistically trained, it makes sense that the behavior will not be completely consistent.

**Comment by alvations** [comment] 2018-08-28 07:18
Closing this issue to clean up the issue tracker. Please do re-open if the issues returns or the `preserve_line` option fails.

**Closed as completed by alvations** 2018-08-28 07:18 UTC
Labels: tokenizer, resolved
