### ISSUE TITLE
Add a CRF POS tagger, replacing the old Mallet interface with CRFSuite

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#104] opened 2012-01-17 06:26 UTC
NLTK's mallet interface, nltk.classify.mallet, is for mallet 0.4.  It
should be upgraded to the current version (which has a different API).

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=523</p>

**Comment by xim** [comment] 2012-04-08 10:02
It might be a good idea to document that we only support Mallet 0.4 (current version is 2.0.7) or drop support entirely.

Current master fails as well:

```
Traceback (most recent call last):
  File "nltk/tag/crf.py", line 760, in <module>
    demo()
  File "nltk/tag/crf.py", line 746, in demo
    acc = nltk.tag.accuracy(crf, brown_test)
AttributeError: 'module' object has no attribute 'accuracy'
```

**Comment by duhaime** [comment] 2013-06-24 12:40
I know this is an old thread, but has this problem been fixed in the current master?

**Comment by kmike** [comment] 2013-06-24 16:06
No, this problem is not fixed.

**Comment by rmunn** [comment] 2013-07-02 05:11
This is a problem for packaging NLTK in Linux distrubutions, specifically Debian and Ubuntu. I worked on the Ubuntu package a while ago, and had to remove the mallet functionality entirely from the Ubuntu package because Ubuntu didn't carry Mallet 0.4 at all. And I was unable to get the NLTK package into Debian, for similar reasons: I started looking at whether I could create a mallet0 package for Debian, got bogged down in Java complexities I wasn't familiar with, and ended up abandoning the Debian NLTK package altogether.

I would like to create a Debian package for NLTK version 3 so that it could be available on both Debian and Ubuntu, but until this issue is resolved one way or the other, I doubt I'll be able to create that Debian package.

**Comment by ewan-klein** [comment] 2013-10-31 06:05
Much of the problem is that mallet.py calls internals.py which adds NLTK_JAR to the Java class path. This is intended to provide a more fine-grained access to parameters that were embedded in the Mallet 0.4 CRF Java code. It is not straightforward to update the Java code that compiles to NLTK_JAR, since it calls classes and fields that are no longer present in Mallet 2.x. I propose that we provide a much simpler interface to the Mallet 2.x CRF classifier which is just a wrapper for cc.mallet.fst.SimpleTagger. I have a crude version of this working now.

**Comment by stevenbird** [comment] 2013-11-28 05:22
If we need to modify the `ClassifierI` interface please move this to the nltk3beta milestone.

**Comment by stevenxxiu** [comment] 2014-02-10 06:38
> It might be a good idea to document that we only support Mallet 0.4 (current version is 2.0.7) or drop support entirely.

I've documented this in the wiki: https://github.com/nltk/nltk/wiki/Installing-Third-Party-Software

**Comment by stevenbird** [comment] 2014-02-10 08:46
@ewan-klein can we drop Mallet 0.4 support from NLTK 3? And then we can see about adding Mallet 2 support later? This would deal with @rmunn's issue finally.

**Comment by ewan-klein** [comment] 2014-02-10 09:54
Yes, this sounds sensible.

**Comment by kmike** [comment] 2014-02-10 10:29
How much simpler is this Mallet interface going to be? I haven't used Mallet myself, but it looks like its main advantage is flexibility - you can use higher-order transition features and stuff like that. 

But if what is needed is a first-order linear chain CRF then there are much faster implementations available like http://wapiti.limsi.fr/ or http://www.chokkan.org/software/crfsuite/. CRFSuite has a "benchmark" page http://www.chokkan.org/software/crfsuite/benchmark.html where it claims to be 100x faster to train than Mallet 2.0.6 on CoNLL 2000 chunking task.

**Comment by stevenbird** [comment] 2014-02-10 10:45
@kmike the idea is to remove the Mallet interface for now. We can obviously consider adding one (or more) CRF interfaces as soon as someone wants to contribute them.

**Comment by ewan-klein** [comment] 2014-02-10 14:09
The potential advantage of Mallet is that is well known and also does topic detection. I agree that if people are looking for high-performance, then other tools might be better. I did some work on fixing the wrapper code, but haven't had time to finish it off. I'd be happy to have someone take it out of my hands!

**Comment by stevenbird** [comment] 2014-02-12 10:27
@rmunn please open a new issue if there are any other obstacles to Linux packaging.

**Comment by stevenbird** [comment] 2014-12-22 23:12
@longdt219 please try to recreate this CRF tagger using the current version of Mallet.

**Comment by longdt219** [comment] 2015-01-18 03:12
Hi @stevenbird, 
Just to be clear, you just want to implement the linear chain CRF POS tagger with supporting the training and testing function ? Mallet also support for <a href = "http://mallet.cs.umass.edu/sequences.php" >  General CRF </a>.  Should we allow user to play with it more (i.e. second-order crf, multi-layer crf) ? Like @kmike said, the best of Mallet is the flexibility. To some extend, we should allow user to tweak it a bit, e.g. jointly predict POS and NER

**Comment by stevenbird** [comment] 2015-01-18 08:40
I like both suggestions. Definitely provide an interface to the linear chain CRF tagger. Before implementing anything more general, please propose the interface, for discussion here.

**Comment by longdt219** [comment] 2015-01-21 11:33
The use can specify the template they going to use in the list of possible templates including 
1. Bigram template 
2. Trigram template 
3. Pairwise template between layers. 
Therefore, the linear chain CRF equivalent to single layer general CRF with bigram template. Second order CRF equivalent to single layer general CRF with trigram template. Pairwise template specify the relation across layers. For example, for jointly predict the POS and NER we will use 
Bigram Template for POS layer, Bigram Template for NER layer and Pairwise template between POS and NER layer. 

This should be simple enough for user to play with.

**Comment by stevenbird** [comment] 2015-01-22 00:03
That sounds reasonable; please go ahead.

**Comment by longdt219** [comment] 2015-01-25 12:36
Hi @stevenbird, 
It turns out that the general CRF doesn't not support for separate training and testing. I implemented the wrapper for the <a href ='http://mallet.cs.umass.edu/sequences.php'> convention  linear chain CRF </a>
I created a <a href='https://github.com/nltk/nltk/pull/855'> pull-request </a> for this.

**Comment by stevenbird** [comment] 2015-01-26 09:27
In #855 we are discussing the idea of using CRFSuite instead of Mallet. There seems to be no reason to provide a Mallet interface. Unless there are any objections, I propose that we provide a CRF tagger using CRFSuite.

**Closed as completed** 2015-03-12 01:43 UTC
