### ISSUE TITLE
BigramTagger not tagging tokens

### ISSUE THREAD

**Issue by mmargegaj** [nltk/nltk#2794] opened 2021-09-01 18:57 UTC
I am trying to create a custom BigramTagger the following way:

```
>>> from nltk.tag.sequential import BigramTagger
>>> model = {'abcd abcd': 'y', 'efgh efgh': 'm'}
>>> bitager = BigramTagger(model=model)
>>> bitager.tag(['abcd abcd', 'efgh efgh'])
[('abcd abcd', None), ('efgh efgh', None)]
```

I'm using nltk version 3.6.2. Am I doing something wrong or this might be a bug?

**Comment by tomaarsen** [comment] 2021-09-02 09:07
A BigramTagger will choose a token's tag based on the token's string and the previous token's tag. This information must then also be included in the model, for it to be useful. I believe your interpretation is that a BigramTagger is a mapping from a string containing both the previous and current token string, to the tag? 

This is not the case. Let me show you how to use the model for a BigramTagger. It is a dictionary of the following structure:
```python
{
    ((prev_tag), tok_string): tok_tag,
    ...
}
```
Assuming that `"abcd abcd"` is 1 token (unlikely!), and `"efgh efgh"` is also 1 token, and the former tags to `"y"` iff it is at the start of the sentence, while the latter tags to `"m"` if it follows a token tagged as `"y"`, then the model becomes:
```python
{
    ((), 'abcd abcd'): 'y',
    (('y',), 'efgh efgh'): 'm'
}
```

If we use this, it works perfectly:
```python
from nltk.tag.sequential import BigramTagger
model = {((), 'abcd abcd'): 'y', (('y',), 'efgh efgh'): 'm'}
bitagger = BigramTagger(model=model)
out = bitagger.tag(["abcd abcd", "efgh efgh"])
```
outputs
```python
[('abcd abcd', 'y'), ('efgh efgh', 'm')]
```

However, I recognise that such a model dict is annoying to make. Luckily, you can just tell NLTK to make (train) one for you. All you would need is a list of tagged sentences.
In the example I made, you have one sentence, with 2 tokens. These are already tagged, so the sentence would be:
```python
[("abcd abcd", "y"), ("efgh efgh", 'm')]
```
A list of these sentences would then be 
```python
[[("abcd abcd", "y"), ("efgh efgh", 'm')]]
```
as we only have one sentence. This can now be used like this:
```python
from nltk.tag.sequential import BigramTagger
train = [[("abcd abcd", "y"), ("efgh efgh", 'm')]]
bitagger = BigramTagger(train=train)
out = bitagger.tag(["abcd abcd", "efgh efgh"])
```

---

However, I recognise that you're likely not intending for e.g. `"abcd abcd"` to be 1 token, so I'll give an example of how the BigramTagger is meant to be used:

```python
from nltk.tag.sequential import BigramTagger
from nltk.corpus import brown

# Get all but the last 100 of the tagged sentences, and last 100 tagged sentences respectively
train = brown.tagged_sents()[:-100]
test = brown.tagged_sents()[-100:]
# A sample tagged sentence (train[0]) is:
# [('The', 'AT'), ('Fulton', 'NP-TL'), ('County', 'NN-TL'), ('Grand', 'JJ-TL'), ('Jury', 'NN-TL'), ('said', 'VBD'), ('Friday', 'NR'), ('an', 'AT'), ('investigation', 'NN'), ('of', 'IN'), ("Atlanta's", 'NP$'), ('recent', 'JJ'), ('primary', 'NN'), ('election', 'NN'), ('produced', 'VBD'), ('``', '``'), ('no', 'AT'), ('evidence', 'NN'), ("''", "''"), ('that', 'CS'), ('any', 'DTI'), ('irregularities', 'NNS'), ('took', 'VBD'), ('place', 'NN'), ('.', '.')]

# Train tagger with all but 100 tagged sentences.
tagger = BigramTagger(train)

# Get a sample untagged sentence
untagged_sentence = brown.sents()[0]
print(f"Input sentence : {untagged_sentence}")
tagged = tagger.tag(untagged_sentence)
print(f"Tagged sentence: {tagged}")

accuracy = tagger.evaluate(test)
print(f"Accuracy: {accuracy * 100:.4f}% between 100 test sentences")
```
This outputs:
```python
Input sentence : ['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of', "Atlanta's", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', "''", 'that', 'any', 'irregularities', 'took', 'place', '.']
Tagged sentence: [('The', 'AT'), ('Fulton', 'NP-TL'), ('County', 'NN-TL'), ('Grand', 'JJ-TL'), ('Jury', 'NN-TL'), ('said', 'VBD'), ('Friday', 'NR'), ('an', 'AT'), ('investigation', 'NN'), ('of', 'IN'), ("Atlanta's", 'NP$'), ('recent', 'JJ'), ('primary', 'NN'), ('election', 'NN'), ('produced', 'VBN'), ('``', '``'), ('no', 'AT'), ('evidence', 'NN'), ("''", "''"), ('that', 'WPS'), ('any', None), ('irregularities', None), ('took', None), ('place', None), ('.', None)]
Accuracy: 19.7816% between 100 test sentences
```

As you can see, the tagger may tag to `None`, and then keep tagging to `None`. This is because the BigramTagger tags based on the previous tag as well as the current string. If it has never seen that combination before, it will tag to `None`. Once that is done, the next token's previous tag will also be `None`, and the model likely doesn't have an answer when the previous token's tag is `None`. 

This is why the BigramTagger is rarely used standalone. A considerably more common scheme is the following, and it is one I would recommend:
```python
from nltk.tag.sequential import BigramTagger, DefaultTagger, UnigramTagger
from nltk.corpus import brown

# Get all but the last 100 of the tagged sentences, and last 100 tagged sentences respectively
train = brown.tagged_sents()[:-100]
test = brown.tagged_sents()[-100:]

def_tagger = DefaultTagger('NN')
uni_tagger = UnigramTagger(train, backoff=def_tagger)
bi_tagger = BigramTagger(train, backoff=uni_tagger)

accuracy = bi_tagger.evaluate(test)
print(f"Accuracy: {accuracy * 100:.4f}% between 100 test sentences")
```
This outputs:
```python
Accuracy: 88.7442% between 100 test sentences
```
In this scheme, we first attempt to apply the BigramTagger. If that is unsuccessful, we apply the UnigramTagger (which doesn't take into account the previous word's tag), and if that one fails too (e.g. if it's a new word), then it simply tags using the DefaultTagger('NN'), which sets the tag to be "NN".

I hope this has been helpful. 

---

I'll close this for now, as this is not a bug, but feel free to reply if you have any questions. And always feel free to let me know if I was wrong, and there is actually a bug.

**Closed as completed** 2021-09-02 09:09 UTC
Labels: tagger, resolved

**Comment by mmargegaj** [comment] 2021-09-02 10:08
Thank you for the detailed answer. It seems I was defining the model structure in a wrong way after upgrading nltk to 3.6.2.
I thought the model can still be declared like I did.
