### ISSUE TITLE
NLTK data path issue coming in GCP / cloud

### ISSUE THREAD

**Issue by pradeepdev-1995** [nltk/nltk#3057] opened 2022-09-30 13:33 UTC
I have deployed one docker-based Microservice in the GCP cloud.

The basic structure in the docker file is as follows
```
FROM python:3.9
RUN apt-get update && apt-get upgrade -y
RUN pip3.9 install nltk==3.6.6
WORKDIR /home/
ADD <Remote customized NLTK path> .
RUN unzip nltk_data.zip
RUN rm -rf nltk_data.zip
RUN ln -s /home/nltk_data /root/nltk_data
```
And then I run one code segment in the MS codebase like

```
import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize("rocks","n"))
lemmatizer.lemmatize("corpora", "n"))
```

But it shows some errors like this

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/usr/local/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource omw-1.4 not found.
  Please use the NLTK Downloader to obtain the resource:



 >>> import nltk
  >>> nltk.download('omw-1.4')
  
  For more information see: https://www.nltk.org/data.html



 Attempted to load corpora/omw-1.4.zip/omw-1.4/



 Searched in:
    - '/root/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************




During handling of the above exception, another exception occurred:



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/onto_logger.py", line 259, in add
    res = func(*args, **kwargs)
  File "/app/ontology_api_development.py", line 15726, in healthcheck
    ol.out_logger.info("rocks is {}".format(lemmatizer.lemmatize("rocks","n")), extra=ol.outlogger_dict)
  File "/usr/local/lib/python3.9/site-packages/nltk/stem/wordnet.py", line 45, in lemmatize
    lemmas = wn._morphy(word, pos)
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/usr/local/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/usr/local/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource omw-1.4 not found.
  Please use the NLTK Downloader to obtain the resource:



 >>> import nltk
  >>> nltk.download('omw-1.4')
  
  For more information see: https://www.nltk.org/data.html



 Attempted to load corpora/omw-1.4



 Searched in:
    - '/root/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************



Transient error StatusCode.UNAVAILABLE encountered while exporting traces, retrying in Nones.
```

Package versions I used in GCP cloud are
```
Python: 3.9.13
OS: Ubuntu non-distroless image
Flask==2.0.3
markupsafe==2.1.1
Flask-Cors==3.0.9
nltk==3.6.6
```

**The same code with the same package versions is working perfectly in my local ubuntu machine without any errors.**
**And the same code with nltk==3.6.5 working perfectly in my local ubuntu machine and GCP also without any errors**
But I must work on nltk==3.6.6 itself.  So errors seems like there is some new nltk data path change pipeline in 3.6.6 version. Please help me to resolve this.

**Comment by tomaarsen** [comment] 2022-09-30 13:57
Hello @pradeepdev-1995,

I see that you've added `nltk_data` manually, and then unzipped it at `/root/nltk_data`. This does seem to be one of the locations that NLTK is checking for data, but in particular it seems to be unable to find `/root/nltk_data/corpora/omw-1.4.zip/omw-1.4/` or `/root/nltk_data/corpora/omw-1.4`. 

Could you verify that for example the latter indeed exists? An expected result is likely something along the lines of:
```
> ls /root/nltk_data/corpora/omw-1.4/
README  arb  citation.bib  dan  fin  heb  isl  iwn  mcr  nld  pol  ron  slv  tha
als     bul  cow           ell  fra  hrv  ita  jpn  msa  nor  por  slk  swe
```

**Comment by pradeepdev-1995** [comment] 2022-10-02 03:40
@tomaarsen 
Thanks for your reply. I checked the above command and it shows like this with docker containerID = 9de6bac6069e. 
```
docker exec 9de6bac6069e ls /root/nltk_data/corpora/omw-1.4/
ls: cannot access '/root/nltk_data/corpora/omw-1.4/': No such file or directory
```
This means my customized NLTK data path doesn't contain such a folder named **omw-1.4** right? Then how does the same NLTK data works with nltk==3.6.5??

**Comment by tomaarsen** [comment] 2022-10-03 11:42
Because omw-1.4 was only introduced to NLTK data on December 8th 2021: https://github.com/nltk/nltk_data/commit/e2e07981c2f09b1c0a847164fa7e4a4fc0297a20 for NLTK 3.6.6. See the changelog here: https://www.nltk.org/news.html

I suspect that your customized NLTK data path doesn't include this folder yet.

**Comment by pradeepdev-1995** [comment] 2022-10-03 11:48
Thank you for the clarification @tomaarsen

**Comment by pradeepdev-1995** [comment] 2022-12-13 04:23
@tomaarsen 
Reopening this issue because the same NLTK=3.6.6 version with  omw-1.4 added NLTK data working well in the **GCP** environment but failing in the **AWS** environment. Again shows the same error in the **AWS** environment.
```
LookupError:
**********************************************************************
  Resource omw-1.4 not found.
  Please use the NLTK Downloader to obtain the resource:



 >>> import nltk
  >>> nltk.download('omw-1.4')
  
  For more information see: https://www.nltk.org/data.html



 Attempted to load corpora/omw-1.4



 Searched in:
    - '/root/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
``` 
The docker commands I have added are as follows
```
FROM python:3.9
RUN apt-get update && apt-get upgrade -y
RUN pip3.9 install nltk==3.6.6
WORKDIR /home/
ADD <Remote customized NLTK path> .
RUN unzip nltk_data.zip
RUN rm -rf nltk_data.zip
RUN ln -s /home/nltk_data /root/nltk_data
```

**Comment by tomaarsen** [comment] 2022-12-13 11:26
Perhaps you could try to run `ls /root/nltk_data/corpora` and seeing if `omw-1.4` and/or `omw-1.4.zip` exists in there. If only the latter exists, then unzipping it and having both `omw-1.4` and `omw-1.4.zip` may work. I've heard of some other people who had issues with certain NLTK data sections not working when zipped.

**Comment by pradeepdev-1995** [comment] 2022-12-15 13:04
@tomaarsen  I can see that there is the folder named ```omw-1.4``` when I put this command  ```ls /root/nltk_data/corpora``` in the environment. **There is no zipped file**. Still, I am getting the above-mentioned **LookupError** error in the AWS environment (K8 Based on deployment). 
How to proceed now?

**Comment by tomaarsen** [comment] 2022-12-16 10:11
I've tried to reproduce the behaviour locally, with only an `omw-1.4` file and no zip file. In my testing, that causes no problems. Could it be that the `/root/` folder is protected (from reading)? That may cause the issue? I can't think of anything else.

**Comment by pradeepdev-1995** [comment] 2022-12-16 10:18
@tomaarsen When I tried with the latest version **nltk==3.8** the issue was resolved.

**Comment by tomaarsen** [comment] 2022-12-16 10:20
Wonderful! I'll close this, then :)

**Closed as completed by tomaarsen** 2022-12-16 10:20 UTC
