### ISSUE TITLE
RegexpTokenizer does not handle capturing parens as advertised

### ISSUE THREAD

**Issue by dlukes** [nltk/nltk#1267] opened 2016-01-24 17:32 UTC
The docstring for `nltk.tokenize.regexp.RegexpTokenizer` states:

```
:param pattern: The pattern used to build this tokenizer.
        (This pattern may safely contain capturing parentheses.)
```

But this does not seem to be the case:

``` python
import nltk
nltk.regexp_tokenize("foo bar baz-qux", r"\w+(-\w+)*")
# returns ['', '', '-qux']
```

Contrast with:

``` python
nltk.regexp_tokenize("foo bar baz-qux", r"\w+(?:-\w+)*")
# returns ['foo', 'bar', 'baz-qux']
```

Tested both with PyPI release (`nltk-3.1`) and current `develop` branch.

**Comment by stevenbird** [comment] 2016-01-24 23:08
Duplicate of #1206.

**Closed as completed** 2016-01-24 23:08 UTC

**Comment by alvations** [comment] 2016-01-24 23:15
@stevenbird Possibly we need to edit the docstrings and tutorials:
- Page 111 of the NLTK book (physically)
- "NLTK's Regular Expression Tokenizer" section on http://www.nltk.org/book/ch03.html
- the [docstrings here](http://www.nltk.org/_modules/nltk/tokenize/regexp.html) looks fine though; I did a quick doctest on `nltk.tokenize.regexp.py` and the expected outputs and outputs were the same.

**Comment by dlukes** [comment] 2016-01-24 23:42
@stevenbird Thanks for ae78614e9751c1230cb13fa815a75fc9f0a2acc1, that's exactly what I had in mind :)

Yes, it would also be a good idea to fix the relevant part of the NLTK book, that's what prompted me to expect capturing groups to work in the first place.

**Comment by alvations** [comment] 2016-01-24 23:46
+1 on https://github.com/nltk/nltk/commit/ae78614e9751c1230cb13fa815a75fc9f0a2acc1
