### ISSUE TITLE
OSError when downloading/unzipping NLTK data (Python 3.5.1)

### ISSUE THREAD

**Issue by sandipchatterjee** [nltk/nltk#1279] opened 2016-01-29 18:56 UTC
I'm getting an OSError when I try to download data via the NLTK command line interface. This occurs when unzipping `corpora/panlex_lite.zip`

Running NLTK 3.1 on Python 3.5.1 (Python installed via Homebrew, NLTK installed via pip) on Mac OS X 10.11.3

Tried running `python3 -m nltk.downloader all` as suggested on http://www.nltk.org/data.html

```
sandip ~> python3 -m nltk.downloader all
[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /Users/sandip/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/sandip/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /Users/sandip/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     /Users/sandip/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     /Users/sandip/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     /Users/sandip/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     /Users/sandip/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     /Users/sandip/nltk_data...
...
[nltk_data]    | Downloading package panlex_lite to
[nltk_data]    |     /Users/sandip/nltk_data...
[nltk_data]    |   Unzipping corpora/panlex_lite.zip.
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/site-packages/nltk/downloader.py", line 2267, in <module>
    halt_on_error=options.halt_on_error)
  File "/usr/local/lib/python3.5/site-packages/nltk/downloader.py", line 664, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/usr/local/lib/python3.5/site-packages/nltk/downloader.py", line 543, in incr_download
    for msg in self.incr_download(info.children, download_dir, force):
  File "/usr/local/lib/python3.5/site-packages/nltk/downloader.py", line 529, in incr_download
    for msg in self._download_list(info_or_id, download_dir, force):
  File "/usr/local/lib/python3.5/site-packages/nltk/downloader.py", line 572, in _download_list
    for msg in self.incr_download(item, download_dir, force):
  File "/usr/local/lib/python3.5/site-packages/nltk/downloader.py", line 549, in incr_download
    for msg in self._download_package(info, download_dir, force):
  File "/usr/local/lib/python3.5/site-packages/nltk/downloader.py", line 638, in _download_package
    for msg in _unzip_iter(filepath, zipdir, verbose=False):
  File "/usr/local/lib/python3.5/site-packages/nltk/downloader.py", line 2039, in _unzip_iter
    outfile.write(contents)
OSError: [Errno 22] Invalid argument
```

**Comment by alvations** [comment] 2016-01-29 19:17
The error could have been caused by a variety of reasons:
- the server hosting the panlex file is somehow busy
- you don't have enough space on your disk on directory that you're working on 
- you don't have extended access to download a file over the net for quite a long period of time
- somehow your internet connection broke while downloading the file

---

If you don't need the `panlex_lite` package, try:

```
$ python
>>> import nltk
>>> nltk.download('all', halt_on_error=False)
```

**Comment by sandipchatterjee** [comment] 2016-01-29 19:42
Thanks, didn't know about the `halt_on_error` parameter. 

I don't need `panlex_lite` at the moment, but I think the issue might not be caused by those reasons mentioned... the issue seems to occur during the `Unzipping corpora/panlex_lite.zip` stage, after the file has already been downloaded, and trying multiple times results in the same error (after downloading the file). Could be an issue with the downloaded file itself?

**Comment by alvations** [comment] 2016-01-29 19:52
Your `panlex_lite.zip` might have been corrupted from multiple download tries. Delete the file from your `nltk_data` directory manually, then redownload the file while you have stable internet connection for quite some minutes. I managed to get it downloaded and unzipped after a pretty long coffee break.

**Comment by sandipchatterjee** [comment] 2016-01-29 20:22
I just tried removing `corpus/panlex_lite.zip` and the `panlex_lite` directory before (re)downloading and ran into the same OSError at the "unzipping" stage. 

I tried running `import nltk;nltk.download('all', halt_on_error=False)` with Python 2.7.11 on my system and the download/unzipping finished successfully for all files, including `panlex_lite.zip`... so maybe something exclusive to Python 3.5? (or some weird issue with my system)

**Comment by alvations** [comment] 2016-01-29 20:24
It's a Python3.5 thing, see #1204

**Comment by alvations** [comment] 2016-04-20 04:05
This issue would have been resolved with the latest version of NLTK, see #1338 for an explanation on why.

**Closed as completed** 2016-04-20 04:05 UTC

**Comment by aravind098** [comment] 2017-03-09 15:51
when i run the command
>>>python -m nltk.downloader all
i get this error
 HTTP Error 503: first byte timeout

**Comment by bora-pajo** [comment] 2017-03-09 15:59
I went back and forth many times until I did the installation right.  If you are running from windows terminal try to install nltk from their site first   
http://pypi.python.org/pypi/nltk
Once you have done that run from terminal
>>>install nltk  

From Mac run from the terminal
>>>sudo pip install -U nltk
then you can import
>>>import nltk
Remember you need python 2.7 or 3.4 to run it correctly.  Hope this helps
