### ISSUE TITLE
ParserI interface

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#620] opened 2014-02-22 00:01 UTC
The behavior of `ParserI.parse` is to return the first (or best) parse or else `None` if no parses exist, while `iter_parse` iterates over all parses, and `nbest_parse` returns a list of n parses. All implementations of `nbest_parse` find all parses before pruning the set. I propose to simplify these to a single `parse` method.

**Comment by heatherleaf** [comment] 2014-02-24 15:13
Fixed in pull request #627

**Comment by heatherleaf** [comment] 2014-02-24 19:14
I suggest that we keep the `n` argument from `nbest_parse` in the `parse` method:

```
def parse(self, sent, n=None):
    """
    :param n: The maximum number of trees to return.
    :type n: int
    """
```

**Comment by stevenbird** [comment] 2014-02-24 23:11
We might want to use a decorator to achieve this (in `api.py`), and that decorator may be useful for any NLTK method that returns an iterator.

**Comment by heatherleaf** [comment] 2014-02-25 06:36
Good idea. Can such an iterator add to the docstring too, and would we want that?

**Comment by stevenbird** [comment] 2014-02-25 06:51
It would be good to update the docstring too. Looks like that's not too difficult: http://stackoverflow.com/questions/13314054/python-decorator-that-maintains-signature-allows-modification-to-docstring-and

**Comment by stevenbird** [comment] 2014-02-25 06:52
However, there's another argument that a programmer can very well select the first n from an iterator without built-in support.

**Comment by heatherleaf** [comment] 2014-02-25 07:28
We already have a function `internals._add_epytext_field()` for this...

**Comment by heatherleaf** [comment] 2014-02-25 07:34
Yes, the programmer can select the first n, but then s/he needs to import itertools:

```
itertools.islice(myparser.parse(sent), N)
```

Not a big problem, but an unexperienced programmer might well try this instead, which is _bad_:

```
list(myparser.parse(sent))[:N]
```

As a comparison:

```
myparser.parse(sent, n=N)
```

**Comment by stevenbird** [comment] 2014-02-25 08:07
OK I'm convinced this is a good idea.

**Comment by heatherleaf** [comment] 2014-02-25 15:03
Here's a decorator that works, but it has one problem:

```
def nbest_iterator(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        n = kwargs.pop('n', None)
        iterator = f(*args, **kwargs)
        if n is not None:
            iterator = itertools.islice(iterator, n)
        return iterator
    _add_epytext_field(wrapper, 'n', "return at most this many results")
    return wrapper
```

Here's an example:

```
>>> @nbest_iterator
... def string_iterator(s):
...     """
...     Converts a string to an iterator
...     @s: the string
...     """
...     return iter(s)
...
>>> list(string_iterator("abcdefg"))
['a', 'b', 'c', 'd', 'e', 'f', 'g']
>>> list(string_iterator("abcdefg", n=3))
['a', 'b', 'c']
>>> help(string_iterator)
Help on function string_iterator in module __main__:

string_iterator(*args, **kwargs)
    Converts a string to an iterator
    @s: the string

    @n: return at most this many results
```

The problem is that the original function signature disappears. I don't like that, the signature is very important for the readability.

**Comment by heatherleaf** [comment] 2014-02-26 10:05
There's another problem with @stevenbird 's original suggestion to make .parse() return an iterator (or a list):

All other NLTK classes that implement a .parse() method return a single result -- ChunkParserI, sem.logic, featstruct, tree. (Even parse.malt and parse.stanford, but these can of course be modified).

Will this be a real problem for the users?

**Comment by stevenbird** [comment] 2014-03-02 01:50
Thanks for pointing out these cases. In the case of sem.logic, featstruct, tree, and RegexpChunkRule, the `parse()` method is being used to convert a string representation of some object into an instance of the object.  It doesn't have to be called parse, and it probably doesn't need to be public either. We could call a hidden method from the initializer (cf the way parse is called from `Tree.__init__()`).

In the case of the chunk parser, the Malt Parser, and the Stanford Parser, we're guaranteed at most one result. While it seems perverse to use an iterator, it seems much worse to return an object instead of a sequence, breaking the interface definition. I think our choices are to return a sequence, or re-introduce the distinction in names (e.g. `nbest_parse()` vs `parse()`).

How about the following solution: `parse()` returns an iterator when this is motivated, else a list? Parsers that return at most one result would return a list which is either empty, or which contains a single tree.

(Note that both the Malt Parser and Stanford Parser provide many other parse-related methods, for different inputs and outputs, none of them defined in `api.py`.)

**Comment by heatherleaf** [comment] 2014-03-02 20:23
Regarding sem.logic, featstruct, etc., I agree that a name change would be good. How about `read_from_string()`?

Regarding the parser API, there is one subtle but important difference between returning an iterator and a list: the empty list is false, but the empty iterator is true. If some parsers return a list, I suspect we will see code like this:

```
trees = p.parse(...)
if not trees:
    REPORT_PARSE_ERROR
else:
    DO_SOMETHING_FOR_ALL_TREES
```

Which won't work for iterators. I prefer to have `parse()` return an iterator in all cases, but we can add two convenience methods in the API:

```
def parse_all(self, ...):
    return list(self.parse(...))
def parse_one(self, ...):
    for tree in self.parse(...):
        return tree
    return None
```

I don't know how to name the combination of `parse_all` and `parse_sents` -- `parse_all_sents` is a bit misleading... The same goes for `parse_one` and `parse_sents`

**Comment by heatherleaf** [comment] 2014-03-05 07:59
So here's my suggestion for the parser api:

```
class ParserI:
    def grammar(self): 
        raise NotImplementedError()
    def parse(self, sent):
        """:rtype: iter(Tree)"""
        if overridden(self.parse_sents):
            return next(self.parse_sents([sent]))
        elif overridden(self.parse_one):
            return (tree for tree in [self.parse_one(sent)] if tree is not None)
        elif overridden(self.parse_all):
            return iter(self.parse_all(sent))
        else:
            raise NotImplementedError()
    def parse_all(self, sent):
        """:rtype: list(Tree)"""
        return list(self.parse(sent))
    def parse_one(self, sent):
        """:rtype: Tree or None"""
        return next(self.parse(sent), None)
    def parse_sents(self, sents):
        """:rtype: iter(iter(Tree))"""
        return (self.parse(sent) for sent in sents)
```

Note that I've changed the return type for `parse_sents()` to return an iterator instead of a list. The input sentences doesn't have to be a list either.

Also note that it is fine for a subclass to implement just one of `parse()`, `parse_one()`, `parse_all()` or `parse_sents()` -- the other methods will accommodate.

Finally, in the current definition of `ParserI.parse()`, there is this line. What is it necessary for?

```
    elif overridden(self.parse):
        return self.parse(sent)
```

**Comment by stevenbird** [comment] 2014-04-21 03:31
Sorry for the delay - I like this proposal, and have dropped it into the API definition in the iter branch here https://github.com/nltk/nltk/commit/51ab82b3e48e5168b2f523f34e15043516084d9b. @heatherleaf if you're still happy with this new interface, would you mind doing any required updates in the parse package please?

**Comment by heatherleaf** [comment] 2014-04-21 19:31
Sure, I can do that. But not until after 10 May.

**Comment by stevenbird** [comment] 2014-04-22 01:12
I took a quick look and think I've found most of them, so I've merged the `iter` branch back into `develop`, and I'll see if the automatic integration testing throws up any errors. I'll fix those and try to get out another test distribution this month.

**Comment by heatherleaf** [comment] 2014-04-23 06:06
Thanks. I'll just lean back and enjoy EACL then…

**Closed as completed** 2014-06-03 08:05 UTC
