### ISSUE TITLE
Reimplement FreqDist

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#86] opened 2012-01-17 06:25 UTC
Reimplement FreqDist to use collections.Counter, in NLTK 3.0.

http://docs.python.org/3.1/library/collections.html?highlight=counter#collections.Counter

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=456</p><hr/><h2>earlier comments</h2>
<p><strong>dchichkov said, at 2010-07-01T22:56:11.000Z:</strong></p>

A few comments:

1) Currently FreqDist is derived from dict(). While it is maybe convenient, it creates extra ambiguities in the interface.

2) Recalculating _N upon every inc() call is wasteful, especially in a way it is done now - via __setitem__ call.

3) For large data sets it is valuable to have a trimming method that deletes samples with frequencies/counts lower than a specified limit;

4) For large data sets it is valuable to have a trimming method that can be called during the data collection process and trims the FreqDist to a specified size (e.g. 100,000,000 samples). This trimming method should delete 'oldest' samples (FIFO basis) with the lowest frequencies. That can be implemented if an OrderedDict is used to store the samples (as an option during the construction).

5) Consider storing samples that occur only once (hapax legomena) in a separate bin (set). Potentially that could reduce memory usage and give overall performance boost. Something along these lines (the code is untested):

```
        self._d = dict()
        self._s = set()
        self._N = 0
        self._Nr_cache = None
        self._max_cache = None
        self._item_cache = None
        if samples:
            self.update(samples)

    def inc(self, sample, count=1):
        """
        Increment this C{FreqDist}'s count for the given
        sample.

        @param sample: The sample whose count should be incremented.
        @type sample: any
        @param count: The amount to increment the sample's count by.
        @type count: C{int}
        @rtype: None
        @raise NotImplementedError: If C{sample} is not a
               supported sample type.
        """
        if count == 0: return
        self._N += count
        if sample in self._d: self._d[sample] += count; return
        if sample in self._s: self._d[sample] = count + 1; self._s.remove(sample); return
        if count == 1: self._s.add(sample); return
        self._d[sample] = count

    def __getitem__(self, sample):
        if sample in self._d: return self._d[sample]
        if sample in self._s: return 1
        return 0

    def __setitem__(self, sample, value):
        """
        Set this C{FreqDist}'s count for the given sample.

        @param sample: The sample whose count should be incremented.
        @type sample: any hashable object
        @param count: The new value for the sample's count
        @type count: C{int}
        @rtype: None
        @raise TypeError: If C{sample} is not a supported sample type.
        """

        self._N += (value - self.__getitem__(sample)))
        if sample in self._d and value <= 1: del delf._d[sample]
        if sample in self._s and value != 1: self._s.remove(sample)
        if value == 1: self._s.add(sample); return
        if value > 1: self._d[sample] = value
```

**Comment by kmike** [comment] 2013-04-08 19:18
collections.Counter is problematic because it is not available in Python 2.6.

Also, what do you think about having a "basic" version of FreqDist interface (static, with unordered keys/values)? 

I played with data structures recently; for Russian Wikipedia unigram counts (untrimmed, lowercased) it takes 40M to store them in IntCompletionDAWG (using https://github.com/kmike/DAWG package), about 90M to store them in hat_trie.Trie (using https://github.com/kmike/hat-trie), about 30M to store them in marisa_trie.Trie (using https://github.com/kmike/marisa-trie + array.array for values ) - and about 700M to store them in nltk.FreqDist. 700M is OK because it could fit to memory on most machines, but for n-grams things could become much worse.

Updating and auto-sorting is not always needed, and these interface requirements makes it harder to create memory-efficient FreqDists (e.g. based on DAWG or Trie).
- FreqDist based on DAWG is easy to build and memory efficient, but it is strictly immutable and can't return items sorted by frequency efficiently;
- FreqDist based on Marisa-Trie is memory efficient and could provide updating of counts and accessing items sorted by frequency (with some work - I have ideas for this), but it is costly to build and there is no way to insert unseen samples after building;
- FreqDist based on HAT-Trie allows inserting and updating of items, but it is less memory efficient (it still could be 5x+ better than FreqDist based on dict), and it can't return items sorted by frequency.

This means none of these solutions could satisfy existing FreqDist interface efficiently, and I think it is better to fix the interface.

DAWG/Marisa-Trie/HAT-Trie are limited to string keys currently; N-grams could be stored there in a simple string form (separated by space).

See also: https://github.com/nltk/nltk/issues/194

**Comment by heatherleaf** [comment] 2013-04-08 20:31
1. I don't think there's a problem that Counter is not available in Py2.6 -- we could fix that easily in compat.py
2. A "basic" FreqDist version is a nice idea. I see two possibilities if we want to retain backwards compatibility, depending on if we want to use a Counter or not:
   
   class UnorderedFreqDist(Counter)
   class FreqDist(UnorderedFreqDist)

alternatively we could use an immutable fd as the base case:

```
class ImmutableFreqDist(object)
class UnorderedFreqDist(ImmutableFreqDist)
class FreqDist(UnorderedFreqDist)
```

**Comment by kmike** [comment] 2013-04-08 21:09
There could be mutable unordered FreqDist (e.g. based on HAT-Trie). Maybe it is possible to separate the data storage (Counter, DAWG, Marisa-Trie) and features provided (Mutable, Ordered)?

Also, "mutable" is ambiguous: sometimes it is possible to update the value, but impossible to insert a new key.

I didn't come with a good design. Java-esque way is to introduce MutableFreqDistI and OrderedFreqDistI abstract base classes. MutableFreqDistI subclasses should provide "inc", "update", "**setitem**", "pop", "popitem" methods; OrderedFreqDistI subclasses should provide "ordered_keys", "ordered_items", "ordered_values" - or just a single "most_common(n)" method (like Counter).

**Comment by stevenbird** [comment] 2013-10-29 03:52
It would be good to resolve this in NLTK3. As @heatherleaf points out, we can provide Counter in compat.py (adopting this implementation http://code.activestate.com/recipes/576611/). We can replace FreqDist with Counter in the book and users will not be wedded to using NLTK for this functionality.

Built-in sort-by-value was provided for the benefit of novices, and it can be inefficient. Its also not semantically transparent: readers of code which iterates over a FreqDist won't necessarily realise that sorting was going on behind the scenes. Counter provides most_common().

Any objections?

**Comment by heatherleaf** [comment] 2013-10-29 08:05
So the suggestion is to still only have one class FreqDist (extending Counter), but to make it unordered? No OrderedFreqDist and no ImmutableFreqDist?

I like simple, so I'm in favour of that.

**Comment by heatherleaf** [comment] 2013-10-29 08:12
There are still FreqDist methods that would be good to show in the book, such as Nr(), hapaxes(), plot() and tabulate(), so don't remove FreqDist completely from the book.

A side note: hapaxes() should return an iterator, not a list.

**Comment by kmike** [comment] 2013-10-29 10:23
I don't quite get it - is the idea to remove FreqDist class or to inherit it from Counter?

**Comment by stevenbird** [comment] 2013-10-29 11:18
I'm now proposing to replace FreqDist with Counter, and figure out how to cover the missing functionality with recipes (e.g. for hapaxes) or utilities (e.g. for plotting). What do you think.

**Comment by kmike** [comment] 2013-10-29 11:21
I like this idea.

**Comment by kmike** [comment] 2013-10-29 11:48
By the way, what do you think about adding ImmutableFreqDist (or "FrozenCounter" or something like this) based on Trie/DAFSA to NLTK? I personally use them quite often because they require much less memory for string data storage. I'm in contact with a local university, and we're going to give students an option to contribute to open-source projects as a coursework; this could be a good task for them. What do you think?

**Comment by stevenbird** [comment] 2013-10-29 12:02
We also need to consider the parallelism with FreqDist/ProbDist, ConditionalFreqDist/ConditionalProbDist.

**Comment by stevenbird** [comment] 2013-10-29 12:04
@kmike: is your question about efficient storage for large sets of words (such as lexicons), where the Trie/DAFSA may be an index (e.g. paths lead to dictionary entries)?

**Comment by kmike** [comment] 2013-10-29 12:19
Yes, something like that. Also, paths may lead to just word counts; this way it is possible to store "frozen" FreqDists and ConditionalFreqDists more efficiently if keys are strings or n-grams. If values are float, it is possible to have "frozen" ProbDists/ConditionalProbDists. It also should be possible to make reqular (not "frozen") ...Dists with string keys using an appropriate version of Trie.

Conditional classes are a bit harder to make compatible with NLTK because of NLTK `cpdist['passed'].prob('VBD')` interface - it would be easier to support `cpdist.prob('passed', 'VBD')`, so I'm using incompatible ConditionalProbDist-like classes for probability distributions; they could be extremely simple, e.g.

```
from dawg import IntCompletionDAWG

class ConditionalProbDistDAWG(IntCompletionDAWG):
    MULTIPLIER = 1000000
    def prob(self, word, tag):
        dawg_key = "%s:%s" % (word, tag)
        return self.get(dawg_key, 0) / self.MULTIPLIER
```

**Comment by kmike** [comment] 2013-10-29 12:31
In Python Trie/DAWG memory savings are coming not only from path compression; C/C++ implementations also remove unnecessary creation of extra Python objects for strings, and the overhead of Python dicts. So it requires 700M to store unigram counts for Russian wikipedia in FreqDist vs 40M for storing them in IntCompletionDAWG. For "unigram counts" task DAWG partially "explodes" to Trie because of counts stored at the end of paths; but even exploded DAWG takes almost 20x less memory than dict. Also, saving-loading of IntCompletionDAWG is much faster than pickling/unpickling because there is no serialization (all data is in a contignous chunk of memory).

**Comment by heatherleaf** [comment] 2013-10-29 12:50
I don't want to replace FreqDist with Counter, but instead redefine it to extend Counter.

**Comment by heatherleaf** [comment] 2013-10-29 12:50
Using DAWG is a nice idea, but we can't rely on it of course, since it is an external module

**Comment by stevenbird** [comment] 2013-10-29 23:27
OK, let's take the more conservative approach for now, and reimplement FreqDist using Counter. This leaves unresolved the efficiency issue (with the sometimes wasteful sorting) and the pedagogical issue (teaching both Counter and FreqDist when they overlap in functionality).

Let's include Counter in compat.py and use it for Python < 2.7 (http://code.activestate.com/recipes/576611/). And let's make sure we can initialize a FreqDist from a Counter (and hopefully vice versa).

**Comment by heatherleaf** [comment] 2013-10-30 06:47
My suggestion was to remove the sorting from FreqDist, so that items/keys/values return in an unspecified order.

plot and tabulate can take an optional sort argument, to specify how the samples should be sorted.

And when we're into it, we should remove sorting from ConditionalFreqDist.conditions() too.

**Comment by stevenbird** [comment] 2013-11-01 03:21
@heatherleaf I agree - there should be no sorting of items/keys/values in FreqDist, or of conditions in ConditionalFreqDist.

FreqDist.samples() should be removed because it provided an unsorted list of keys which we will now access using FreqDist.keys().

FreqDist.iteritems/keys/values() should be removed because the non-iterator versions of these methods in Python 3 will return iterators anyway (and we will not bother to maintain iterator versions for users of Python 2).

FreqDist.update() can be replace by the pipe operator (e.g. fd1 |= fd2).

**Comment by heatherleaf** [comment] 2013-11-01 08:22
FreqDist.update() can be replace by Counter.update(), it has the same meaning

|= and | has totally different semantics: they calculate the maximum

+= and + are almost the same as update(), but they need a Counter on the righthandside whereas update() can take any sequence

**Comment by stevenxxiu** [comment] 2013-11-01 08:38
I'm not sure I understand the implementation of `B()`, as it produces the total number of bins, not just those greater than 0 as said in the docs, as an example: `FreqDist({'bin':-1}).B()==1`. Should negative counts be allowed in `FreqDist` (they are allowed in `Counter`)?

**Comment by heatherleaf** [comment] 2013-11-01 08:45
So there are not many methods that needs to be kept, and most of them are just for convenience. This is my suggestion:

```
B(self) == len(self)
N(self) == sum(self.values())
Nr(self, r, bins=None) == sum(count==r for count in self.values()) # with a special case for r==0
freq(self, sample) == self[sample] / self.N()
hapaxes(self) == (sample for sample, count in self.items() if count == 1)
inc(self, sample, count=1) == self[sample] += count
max(self) == self.most_common(1)[0][0]
plot(self, ...)
tabulate(self, ...)
```

There is one minor problem with Counter: the str() representation shows ALL samples and counts in decreasing order, which takes time and space for large objects (which we often work with). So my suggestion is to rewrite it for FreqDist. Either as before or with the N most common samples:
- `<FreqDist with 123 samples and 321 outcomes>`
- `FreqDist({'a':13, 'j':10, 'q':8, ...})`

**Comment by heatherleaf** [comment] 2013-11-01 08:48
@jskda: Counters accept negative values, but the operators (+ . & |) discards them. Quoted from the docs:

```
Unary addition and substraction are shortcuts for adding an empty counter or subtracting from an empty counter.
>>> c = Counter(a=2, b=-4, c=0)
>>> +c
Counter({'a': 2})
>>> -c
Counter({'b': 4})
>>> len(c)
3
>>> len(+c)
1
```

**Comment by heatherleaf** [comment] 2013-11-01 08:50
So we could decide to define B like this instead:

```
B(self) = len(+self)
```

But this makes things slower, because it has to build a new Counter

**Comment by heatherleaf** [comment] 2013-11-01 08:55
There is a subtle difference between .update() and += in how they treat negative values:

```
>>> c = Counter(a=2)
>>> c += Counter(a=-3)
>>> c
Counter()
>>> d = Counter(a=2)
>>> d.update(Counter(a=-3))
>>> d
Counter({'a': -1})
```

**Comment by stevenxxiu** [comment] 2013-11-01 08:56
Thanks, good idea for `B()`.
Here's my implementation of your suggested `str()` representation:

```
def __str__(self, maxlen = 10):
    """
    Return a string representation of this FreqDist.

    :rtype: string
    """
    items = ['{0!r}: {1!r}'.format(*item) for item in self.most_common(maxlen)]
    if len(self) > maxlen:
        items.append('...')
    return 'FreqDist({{{0}}})'.format(', '.join(items))
```

I've added a `maxlen` argument to specify how short the representation should be.

**Comment by heatherleaf** [comment] 2013-11-01 08:57
But defining `B(self)=len(+self)` this makes things slower, because it has to build a new Counter every time. And we're working with large counters here.

```
$ python3 -m timeit -n 10 -s 'from collections import Counter; c=Counter(range(10**6))' -- 'len(+c)'
10 loops, best of 3: 1.35 sec per loop

$ python3 -m timeit -n 10 -s 'from collections import Counter; c=Counter(range(10**6))' -- 'len(c)'
10 loops, best of 3: 0.656 usec per loop
```

**Comment by stevenxxiu** [comment] 2013-11-01 09:09
I'm thinking it could be cached on a call to `len` or whenever there's a modification to `FreqDist`.

**Comment by heatherleaf** [comment] 2013-11-01 09:12
Oh, and there's another method we have to consider:

```
def _Nr_nonzero(self):
    """Return (r, Nr(r)) tuples for all r such as Nr(r) > 0 (sorted by r)."""
```

This is used by `SimpleGoodTuringProbDist._r_Nr()`, which in turn is used by its `__init__`.

It's not good practise to have a method starting with `_` which is used outside the class. We should consider renaming it. (And remove sorting of course).

**Comment by stevenxxiu** [comment] 2013-11-01 09:13
Thats a good idea, I think it should also be lower case, so we conform to PEP-8.

**Comment by stevenxxiu** [comment] 2013-11-01 09:47
The unary `+` operator is only support in python 3.3, but for earlier python versions adding an empty Counter will do.

**Comment by heatherleaf** [comment] 2013-11-05 08:07
@jskda: I just did some timing tests, and it's faster to calculate .N() on demand (and caching the result), than using a specific ._N counter that needs to change after each update. So, this is faster than your current solution:

```
def _reset_caches(self):
    self._Nr_cache = None
    self._N = None

def N(self):
    if self._N is None:
        self._N = sum(self.values())
    return self._N
```

I created a FreqDist over the Brown corpus and calculated .N(), and using the about approach is 25% faster. It's also 25% faster when I tried just a portion of Brown.

The only time when the current approach is faster is if you want to calculate .N() while still building the FreqDist, but I think that's very uncommon.

**Comment by heatherleaf** [comment] 2013-11-05 08:21
Hmm… I just noticed that it's 3x faster to build a Counter than a FreqDist, even using the optimized variant above. I guess the problem is that FreqDist calls `_reset_caches()` from `__setitem__()`. 

Is there something we can do about this? @kmike, @jskda, @stevenbird?

**Comment by stevenbird** [comment] 2013-11-06 01:00
Thanks for this @heatherleaf. So, the only remaining cached information is for Nr, the number of items with frequency r. I guess language model smoothing algorithms use this heavily. Perhaps any necessary optimisations should be done in that code, or else provided as an option here, and only switched on by that code? We certainly shouldn't have such a big overhead for creating a FreqDist.

**Comment by heatherleaf** [comment] 2013-11-06 07:43
It seems like it's only SimpleGoodTuringProbDist that uses `_Nr_nonzero()`, so I guess it could cache that information itself.

So here's a suggestion:
- Remove all FreqDist caches.
- Replace `_Nr_nonzero()` and `_cache_Nr_values()` with a "public" method `Nr_nonzero()` that does the calculation every time it is called. 
- The same for `N()`: it can be calculated by `sum(self.values())` 
- And the same for `max()`: it can be calculated by `max(self, key=self.get)` or (slightly faster) `max(self, key=self.__getitem__)`

This might have some effects, and the smallest problem is Nr_nonzero:
- SimpleGoodTuringProbDist can cache `Nr_nonzero()`, no problem.
- `max()` is defined by all ProbDists, and some of them calls `FreqDist.max()`
  - these in turn seem to be used in modules `classify.decisiontree`, `classify.maxent`, `classify.naivebayes`, `tag.hmm`, `tag.sequential` and `test.unit.test_naivebayes`
- `N()` is also defined by ConditionalFreqDist, and used in several places in `probability`
  - it is also used in modules `collocations`, `app.wordfreq_app`, `classify.decisiontree`, `classify.naivebayes`, `classify.positivenaivebayes`, `tag.tnt` and `tokenize.punkt`
- I don't know how many of these assume that the value is cached.

**Comment by heatherleaf** [comment] 2013-11-06 07:43
I guess we should do it in steps: first get a FreqDist(Counter) to work, and then remove the caches one at the time.

**Comment by stevenbird** [comment] 2013-11-07 05:57
I suggest we dispense with caching entirely, and modify SimpleGoodTuringProbDist as necessary, also other methods that relied on FreqDist.Nr(). Please see: https://github.com/nltk/nltk/pull/544

**Comment by stevenbird** [comment] 2013-11-25 04:52
Resolved in https://github.com/nltk/nltk/commit/ace06f6de5d418f8e477108d03d4d991e6ff7987

**Closed as completed by stevenbird** 2013-11-25 04:52 UTC
