### ISSUE TITLE
TreebankWordDetokenizer does not detokenize to original string

### ISSUE THREAD

**Issue by arendu-zz** [nltk/nltk#2802] opened 2021-09-11 05:28 UTC
Hi, I am trying to tokenize replace a token and then detokenize a string. I am noticing that detokenize does not "undo" the tokenization correctly. Here is a example:
```
>>> import nltk
>>> _tokenizer = nltk.tokenize.treebank.TreebankWordTokenizer()
>>> _detokenizer = nltk.tokenize.treebank.TreebankWordDetokenizer()
>>> f = "here, is an email: me@mail.com"
>>> _detokenizer.detokenize(_tokenizer.tokenize(f))
'here, is an email: me @ mail.com'
```

I was expecting the email to be detokenized back to me@mail.com. This seems like a bug.
I'm using nltk version 3.6.2

**Comment by 12mohaned** [comment] 2021-09-12 12:15
Hi @arendu, 

Hope you are doing well, 

I believe, it is better to use the [TwitterTokenizer](https://www.nltk.org/api/nltk.tokenize.html#module-nltk.tokenize.casual) to tokenise data that contains email, hashtags, and emoji instead of treebank or any other tokeniser, since it is better aimed at it. 

I hope, the below code answer your need.

```
import nltk
from nltk.tokenize import TweetTokenizer
tweet_tokenizer = TweetTokenizer()
_detokenizer = nltk.tokenize.treebank.TreebankWordDetokenizer()
f = "here, is an email: me@mail.com"
_detokenizer.detokenize(tweet_tokenizer.tokenize(f))
```

output: 
> here, is an email: me@mail.com

So, it is not a bug, but I believe Treebank tokeniser is not trained to deal with such kind of data. 

Regards.

**Comment by tomaarsen** [comment] 2021-09-12 21:02
The Treebank Detokenizer isn't guaranteed to return to exactly the input used in the Treebank Tokenizer, sadly. I believe this is simply a consequence of the Treebank Tokenizer not being bijective. With other words, both `'me @ mail.com'` and `'me@mail.com'` will tokenize to `['me', '@', 'mail.com']` (because the Treebank tokenizer is indeed not designed for emails, as @12mohaned rightfully mentioned). Then, upon applying that tokenized list to the detokenizer, it cannot possibly know whether the original was `'me @ mail.com'` or `'me@mail.com'`.

Mohaned has provided a good solution to this problem, I believe.

I'll close this issue as I don't believe this is a bug, and a solution has been proposed. Feel free to respond if you need some additional help or if you do believe that this is an issue that ought to be resolved.

**Closed as completed by tomaarsen** 2021-09-12 21:02 UTC
Labels: tokenizer, resolved

**Comment by arendu-zz** [comment] 2021-09-12 22:53
Thanks @12mohaned and @tomaarsen! I will use the tweettokenizer.
