### ISSUE TITLE
the BLEU socre calculated by the version 3.4 is different from the version 3.2

### ISSUE THREAD

**Issue by jiaxin96** [nltk/nltk#2245] opened 2019-03-03 03:55 UTC
run this code:
from nltk.translate.bleu_score import sentence_bleu
reference = [['the', 'cat',"is","sitting","on","the","mat"]]
test = ["on",'the',"mat","is","a","cat"]
score = sentence_bleu(  reference, test)
print(score)

version 3.2 print:
0.4548019047027907
/home/jren/anaconda3/lib/python3.6/site-packages/nltk/translate/bleu_score.py:490: UserWarning: 
Corpus/Sentence contains 0 counts of 4-gram overlaps.
BLEU scores might be undesirable; use SmoothingFunction().
  warnings.warn(_msg)

version 3.4 print:
D:\ProgramData\Anaconda3\lib\site-packages\nltk\translate\bleu_score.py:523: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
5.5546715329196825e-78

**Comment by alvations** [comment] 2019-05-03 16:09
@jiaxin96 Thanks for raising the issue. 

As the warning suggests, the scores for BLEU isn't stable once there's not at least one 4-gram matches between the reference and the hypothesis. 

Previously 3.2 had non-traditional BLEU techniques that mitigates the problem by backing off to the largest n-gram matches but #1844 changed the BLEU to traditional BLEU score that matches that of Mosesdecoder.

**Comment by alvations** [comment] 2019-05-07 05:25
Closing issue as resolved. Please re-open if the issue is still relevant/unresolved.

**Closed as completed by alvations** 2019-05-07 05:25 UTC
Labels: SMT, resolved
