### ISSUE TITLE
Python 2/3 encoding issue

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#788] opened 2014-11-07 04:58 UTC
Python 2 and 3 give different errors for a character encoding issue. It shows up in the `StanfordParser` and `StanfordTokenizer` errors in the latest test results. The problem was triggered by a seemingly unrelated commit of mine concerning the ChunkParser. @kmike I would be grateful for any advice.

https://nltk.ci.cloudbees.com/job/nltk/

**Comment by kmike** [comment] 2014-11-07 12:35
The error is caused by a test runner which replaces sys.stdout with a `_SpoofOut` stub which doesn't have 'encoding' property. I've commited a fix - could you please check if it helped?

**Comment by stevenbird** [comment] 2014-11-14 23:55
Thanks @kmike for the fix. Unfortunately we still have a problem, reported by our [integration testing](https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py32-jenkins/lastCompletedBuild/testReport/nltk.parse/stanford/StanfordParser/).

```
File "/scratch/jenkins/workspace/nltk/TOXENV/py32-jenkins/nltk/internals.py", line 653, in _decode_stdoutdata
        return stdoutdata.decode(encoding)
    TypeError: decode() argument 1 must be str, not None
```

**Comment by kmike** [comment] 2014-11-17 05:08
Sorry, I missed it. In Python 2.6 it fails with another [error](https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py26-jenkins/138/testReport/junit/nltk.parse/stanford/StanfordParser/): 

```
File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/nltk/parse/stanford.py", line 32, in nltk.parse.stanford.StanfordParser
Failed example:
    parser.raw_parse_sents((
        "the quick brown fox jumps over the lazy dog",
        "the quick grey wolf jumps over the lazy fox"
    ))
Exception raised:
    Traceback (most recent call last):
      File "/scratch/jenkins/python/python-2.6.9-x86_64/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest nltk.parse.stanford.StanfordParser[1]>", line 3, in <module>
        "the quick grey wolf jumps over the lazy fox"
      File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/nltk/parse/stanford.py", line 176, in raw_parse_sents
        return self._parse_trees_output(self._execute(cmd, '\n'.join(sentences), verbose))
      File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/nltk/parse/stanford.py", line 236, in _execute
        stdout=PIPE, stderr=PIPE)
      File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/nltk/internals.py", line 161, in java
        raise OSError('Java command failed!')
    OSError: Java command failed!
```

**Comment by longdt219** [comment] 2014-12-15 08:06
I don't know but using these might help. 
sys.__stdout__
sys.__stderr__

These objects contain the original values of stdin, stderr and stdout at the start of the program. They are used during finalization, and could be useful to print to the actual standard stream no matter if the sys.std\* object has been redirected.

I committed the code (new pull request), could you check @stevenbird

**Closed as completed** 2014-12-16 01:02 UTC
