### ISSUE TITLE
Bug in portuguese text

### ISSUE THREAD

**Issue by mrcomac** [nltk/nltk#2283] opened 2019-05-03 13:30 UTC
Hi!

I'm using the exemple code from:
https://github.com/parulnith/Building-a-Simple-Chatbot-in-Python-using-NLTK

I changed the code in the line 23:
`word_tokens = nltk.word_tokenize(raw)# converts to list of words`
to
`word_tokens = nltk.word_tokenize(raw, language='portuguese')# converts to list of words
`
And the line 61 from:
` TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')`
to
` TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words=stopwords.words('portuguese'))`

When I use a portuguese(brazilian) text with letter "í" I get this error:
`Traceback (most recent call last):
  File "chatbot.py", line 22, in <module>
    sent_tokens = nltk.sent_tokenize(raw)# converts to list of sentences 
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/__init__.py", line 105, in sent_tokenize
    return tokenizer.tokenize(text)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1277, in tokenize
    return list(self.sentences_from_text(text, realign_boundaries))
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1331, in sentences_from_text
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1321, in span_tokenize
    for sl in slices:
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1362, in _realign_boundaries
    for sl1, sl2 in _pair_iter(slices):
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 321, in _pair_iter
    for el in it:
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1337, in _slices_from_text
    if self.text_contains_sentbreak(context):
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1383, in text_contains_sentbreak
    for t in self._annotate_tokens(self._tokenize_words(text)):
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 1519, in _annotate_second_pass
    for t1, t2 in _pair_iter(tokens):
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 318, in _pair_iter
    prev = next(it)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 599, in _annotate_first_pass
    for aug_tok in tokens:
  File "/usr/local/lib/python2.7/dist-packages/nltk/tokenize/punkt.py", line 561, in _tokenize_words
    for line in plaintext.split('\n'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)`

for the 'ã', 'ç' and others there isn't error.

**Comment by alvations** [comment] 2019-05-03 16:00
@marcosmachado81 The code that you've referred to have not specified encoding of the file. Please see the minor changes made to the pull request at https://github.com/parulnith/Building-a-Simple-Chatbot-in-Python-using-NLTK/pull/1

**Comment by alvations** [comment] 2019-05-07 05:24
Closing issue as resolved. Please re-open if the issue is still relevant/unresolved.

**Closed as completed by alvations** 2019-05-07 05:24 UTC
Labels: Off-topic, resolved, third-party
