### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by shsarv** [nltk/nltk#2580] opened 2020-08-11 07:34 UTC
'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg)).

**Comment by bodograumann** [comment] 2020-11-19 12:34
Duplicate of https://github.com/nltk/nltk/issues/2162

**Closed as completed** 2020-12-23 09:11 UTC
