### ISSUE TITLE
UnicodeDecodeError with nltk.pos_tag

### ISSUE THREAD

**Issue by w0rm79** [nltk/nltk#889] opened 2015-02-19 05:48 UTC
Hi!

The following function call 

```
nltk.pos_tag(nltk.word_tokenize("And now for something completely different"))'
```

results with error:

```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    nltk.pos_tag(nltk.word_tokenize("And now for something completely different"))
  File "C:\Anaconda3\lib\site-packages\nltk\tag\__init__.py", line 100, in pos_tag
    tagger = load(_POS_TAGGER)
  File "C:\Anaconda3\lib\site-packages\nltk\data.py", line 779, in load
    resource_val = pickle.load(opened_resource)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 0: ordinal not in range(128)
```

I have tried with two nltk versions from anaconda: `3.0.0 np19py34_0` and `3.0.1 np19py34_0`. Python version string is `Python 3.4.1 |Anaconda 2.1.0 (32-bit)| (default, Sep 24 2014, 18:34:57) [MSC v.1600 32 bit (Intel)] on win32`.

Any ideas how to get rid of this problem?

Thanks,

Jani

**Comment by w0rm79** [comment] 2015-02-19 06:15
Ok!

I was actually able to solve this out. The problem is in `nltk.tag.__init__.py`:

```
# Standard treebank POS tagger
_POS_TAGGER = 'taggers/maxent_treebank_pos_tagger/english.pickle'
def pos_tag(tokens):
```

For Python 3 this should be instead

```
# Standard treebank POS tagger
_POS_TAGGER = 'taggers/maxent_treebank_pos_tagger/PY3/english.pickle'
def pos_tag(tokens):
```

Maybe someone knows how to make this dynamic based on Python version.

Jani

**Comment by stevenbird** [comment] 2015-02-21 18:32
This is a duplicate of #840, and will appear in version 3.0.2.

**Closed as completed by stevenbird** 2015-02-21 18:32 UTC
