### ISSUE TITLE
Failing tests in DocStrings

### ISSUE THREAD

**Issue by ekaf** [nltk/nltk#2989] opened 2022-05-01 06:28 UTC
Checking the Python files in NLTK with "python -m doctest" reveals that many tests are failing. In many cases, the failures are just cosmetic discrepancies between the expected and the actual output, such as missing a blank line, or unescaped linebreaks. Other cases may be real bugs.

If these failures could be avoided, it would become possible to improve CI by running "python -m doctest" each time a python file was modified.

Here is an updated list, after applying #2990, and unzipping those corpora marked unzip="1":

> nltk/parse/corenlp.py: 9 passed and 33 failed.
nltk/parse/stanford.py: 1 passed and 16 failed.
nltk/corpus/reader/framenet.py: 79 passed and 9 failed.
nltk/tokenize/regexp.py: 14 passed and 7 failed.
nltk/draw/table.py: 0 passed and 6 failed.
nltk/tokenize/simple.py: 7 passed and 6 failed.
nltk/text.py: 16 passed and 5 failed.
nltk/tokenize/stanford_segmenter.py: 3 passed and 5 failed.
nltk/draw/util.py: 1 passed and 4 failed.
nltk/tag/hunpos.py: 1 passed and 4 failed.
nltk/tokenize/__init__.py: 6 passed and 4 failed.
nltk/translate/ibm1.py: 12 passed and 4 failed.
nltk/tag/brill_trainer.py: 23 passed and 3 failed.
nltk/tokenize/destructive.py: 8 passed and 3 failed.
nltk/tokenize/treebank.py: 32 passed and 3 failed.
nltk/tokenize/util.py: 27 passed and 3 failed.
nltk/translate/meteor_score.py: 8 passed and 3 failed.
nltk/corpus/reader/categorized_sents.py: 5 passed and 2 failed.
nltk/corpus/reader/opinion_lexicon.py: 3 passed and 2 failed.
nltk/corpus/reader/reviews.py: 8 passed and 2 failed.
nltk/metrics/agreement.py: 8 passed and 2 failed.
nltk/parse/dependencygraph.py: 13 passed and 2 failed.
nltk/parse/evaluate.py: 6 passed and 2 failed.
nltk/parse/util.py: 5 passed and 2 failed.
nltk/tag/stanford.py: 2 passed and 2 failed.
nltk/tokenize/stanford.py: 3 passed and 2 failed.
nltk/corpus/__init__.py: 1 passed and 1 failed.
nltk/corpus/reader/comparative_sents.py: 5 passed and 1 failed.
nltk/corpus/reader/__init__.py: 1 passed and 1 failed.
nltk/corpus/reader/pros_cons.py: 2 passed and 1 failed.
nltk/probability.py: 39 passed and 1 failed.
nltk/sentiment/util.py: 7 passed and 1 failed.
nltk/stem/arlstem2.py: 3 passed and 1 failed.
nltk/stem/rslp.py: 3 passed and 1 failed.
nltk/stem/snowball.py: 6 passed and 1 failed.
nltk/tag/__init__.py: 12 passed and 1 failed.
nltk/tokenize/casual.py: 9 passed and 1 failed.
nltk/translate/ibm2.py: 18 passed and 1 failed.
nltk/translate/ibm3.py: 23 passed and 1 failed.
nltk/translate/ibm4.py: 25 passed and 1 failed.
nltk/translate/ibm5.py: 22 passed and 1 failed.

**Comment by Madnex** [comment] 2022-07-11 07:01
Is anyone working on this? I would be happy to pick it up and improve the tests.

**Comment by tomaarsen** [comment] 2022-07-11 09:43
Not to the best of my knowledge. Feel free to pick this up @Madnex!

**Comment by Madnex** [comment] 2022-08-22 08:14
Hi! I have managed to fix most of the tests. However I have issues with the following ones:

1. `nltk/parse/corenlp.py: 9 passed and 33 failed.` 
I am getting errors indicating that the local server is not running that is needed for parsing.

2. `nltk/tag/hunpos.py: 1 passed and 4 failed.` 
The hunpos-tag file and the en_wsj.model file were not found

3. `nltk/parse/dependencygraph.py: 13 passed and 2 failed.`
I am getting the error `Exception: Cannot find the dot binary from Graphviz package`.
 
4. `nltk/draw/table.py: 0 passed and 6 failed. `
When I try to run the code I get an error `AttributeError: 'SpaceWidget' object has no attribute 'tk'`

Are those errors related to my configuration? Or do you also encounter them?


Additionally, the errors in those four files I did not fix: 
- nltk/parse/stanford.py: 1 passed and 16 failed. (deprecated)
- nltk/tag/stanford.py: 2 passed and 2 failed. (deprecated)
- nltk/tokenize/stanford.py: 3 passed and 2 failed. (deprecated)
- nltk/tokenize/stanford_segmenter.py: 3 passed and 5 failed. (deprecated)

There I get deprecation errors / warnings. Should they be ignored / removed?

**Comment by tomaarsen** [comment] 2022-08-22 08:39
Good work!

I've experienced issues 1 through 3 that you listed. These make some sense, as these services simply require some additional setup. That said, the 4th one is odd. That might be indicative of some actual bugs.

As for the deprecated errors, we'll end up wanting to include the doctests in the CI check, so we should probably ensure that all tests pass. In that case, we might want to either remove the tests for the deprecated work, or modify them such that they're skipped. (I prefer the latter).

I would hope to use `pytest --doctest-modules .\nltk\` to run the doctests easily, but I'm running into issues there, likely because of our LazyLoaders:
```
...\lib\doctest.py:939: in find
    self._find(tests, obj, name, module, source_lines, globs, {})
.env39\lib\site-packages\_pytest\doctest.py:522: in _find
    doctest.DocTestFinder._find(  # type: ignore
...\lib\doctest.py:995: in _find
    for valname, val in obj.__dict__.items():
E   RuntimeError: dictionary changed size during iteration
```

Are you aware of a way to easily run the doctests perhaps?

**Comment by Madnex** [comment] 2022-08-22 08:57
Okay, so is there a way to include issues 1-3 in the tests for the CI if we need specific setups?
For the issue 4 I think it is a bug then. I will try to see where it's going wrong exactly.

I will add a `+SKIP` for the deprecated tests as suggested.

I don't know how to run the doctests all at once. Maybe @ekaf has more info on this?

**Comment by tomaarsen** [comment] 2022-08-22 09:06
Issues 1-3 can be included in the CI, but only with a lot of additional work. I would argue that it's not worth it. We have done something similar in the past for some of the "regular" tests. See our CI job which downloads and caches third party resources:
https://github.com/nltk/nltk/blob/3b72fa2b3dea0088cd6d15d4409ce52318a3d1a0/.github/workflows/ci.yaml#L53-L72
And the script it actually executes: https://github.com/nltk/nltk/blob/develop/tools/github_actions/third-party.sh

---

However, I think the best solution here is to have a conditional skip. 
For example, see the following snippets:
https://github.com/nltk/nltk/blob/3b72fa2b3dea0088cd6d15d4409ce52318a3d1a0/nltk/test/inference.doctest#L4-L9
https://github.com/nltk/nltk/blob/3b72fa2b3dea0088cd6d15d4409ce52318a3d1a0/nltk/test/inference_fixt.py#L1-L10

In the doctest, we import the code below, which performs a lookup step to check whether the required resource is installed/downloaded. If it is not, then we skip the test. This is a bit of a hacky solution sadly. I'm not sure what the most convenient implementation for this is.

**Comment by tomaarsen** [comment] 2022-08-22 10:35
> I would hope to use `pytest --doctest-modules .\nltk\` to run the doctests easily, but I'm running into issues there, likely because of our LazyLoaders:

> I don't know how to run the doctests all at once. Maybe @ekaf has more info on this?

I've looked into the reason that `pytest --doctest-modules .\nltk\` was failing. It should be fixed after #3033. That way, we will be able to modify the following line from `nltk/test` to `nltk`:
https://github.com/nltk/nltk/blob/3b72fa2b3dea0088cd6d15d4409ce52318a3d1a0/.github/workflows/ci.yaml#L128

And then it will automatically work with all doctests.

**Comment by Madnex** [comment] 2022-08-22 13:31
Wow, thanks for the quick fix 👍

**Comment by ekaf** [comment] 2022-08-23 06:06
Of the 2 doctests failures in File "nltk/parse/dependencygraph.py", only the first is caused by missing the dot binary from Graphviz package.

The second failure reveals a genuine problem in the module: 

> File "nltk/parse/dependencygraph.py", line 461, in dependencygraph.DependencyGraph.contains_cycle
> Failed example:
>     cyclic_dg.contains_cycle()
> Expected:
>     [3, 1, 2, 4]
> Got:
>     [1, 2, 4, 3]
> 

There could be non-determinism in the implementation of _contains_cycle()_, eventually caused by iterations over randomly ordered dictionary keys, or is the expected doctest output just wrong?

**Comment by ekaf** [comment] 2022-08-24 08:59
I used the following script to run all the tests in one batch:

```
#!/bin/sh

#ln -s nltk PATH_to_nltk
mkdir out

for f in `find nltk/* -type f -name '*py' -print`
do
python -m doctest -v $f|tee out/`echo -n $f|tr "/" "!"`
done

cd out
grep "passed and" nltk*py|grep -v " 0 failed"|tr "!" "/"|tee Out-doctests

```

**Comment by ekaf** [comment] 2022-08-25 06:20
The two approaches differ in the way they handle bugs found outside the doctests: while 'python -m doctest' only prints a warning to stderr, 'pytest --doctest-modules nltk' prints the error to stdout, and seems to only be able to process a few files before getting stuck.

> 
> _______________ ERROR collecting nltk/corpus/reader/markdown.py ________________
> nltk/corpus/reader/markdown.py:4: in <module>
>     from markdown_it import MarkdownIt
> E   ModuleNotFoundError: No module named 'markdown_it'
>

**Comment by Madnex** [comment] 2022-08-29 08:43
> https://github.com/nltk/nltk/issues/2989#issuecomment-1222068304

I'm having issues implementing this workaround. I added the `setup_module()` inside the `hunpos.py`.

```
  class HunposTagger(TaggerI):
      """
      A class for pos tagging with HunPos. The input is the paths to:
       - a model trained on training data
       - (optionally) the path to the hunpos-tag binary
       - (optionally) the encoding of the training data (default: ISO-8859-1)
  
      Check for available files
          >>> from nltk.test.hunpos_fixt import setup_module
          >>> setup_module()
```
However, when running a pytest on this file the error is raised including the skipped part:

`
  raise Skipped(msg=reason, allow_module_level=allow_module_level)
        Skipped: Hunpos file is not available so hunpos doctest was skipped
`

Would I need to separate the doctests from the `hunpos.py` file to e.g. a `hunpos.doctest` file?

**Comment by ekaf** [comment] 2022-08-31 12:20
After applying PR #3033 by @tomaarsen, "pytest --doctest-modules ./nltk/" works fine for finding which files have at least one error. For example, in the "tag" subdirectory:

> nltk/tag/brill_trainer.py:126: DocTestFailure
> nltk/tag/hunpos.py:36: UnexpectedException
> nltk/tag/stanford.py:150: UnexpectedException
> 

However, this approach does not find _all_ errors, which is what is needed when one wants to debug the whole file, and what "python -m doctest" does (https://github.com/nltk/nltk/issues/2989#issuecomment-1225436256):

> nltk/tag/\_\_init\_\_.py:12 passed and 1 failed.
> nltk/tag/brill_trainer.py:23 passed and 3 failed.
> nltk/tag/hunpos.py:1 passed and 4 failed.
> nltk/tag/stanford.py:2 passed and 2 failed.

The additional test failure in \_\_init\_\_.py is a question of floating point test accuracy. I think it has been circumvented in pytest by a PR.

**Comment by ekaf** [comment] 2022-09-01 08:00
For debugging, pytest's "--doctest-continue-on-failure" may be handy in order to obtain more complete figures:

`pytest --doctest-modules --doctest-continue-on-failure ./nltk/tag/`

> nltk/tag/brill_trainer.py:126: DocTestFailure
> nltk/tag/brill_trainer.py:176: DocTestFailure
> nltk/tag/brill_trainer.py:213: DocTestFailure
> nltk/tag/hunpos.py:36: UnexpectedException
> nltk/tag/hunpos.py:37: UnexpectedException
> nltk/tag/hunpos.py:39: UnexpectedException
> nltk/tag/hunpos.py:46: UnexpectedException
> nltk/tag/stanford.py:150: UnexpectedException
> nltk/tag/stanford.py:151: UnexpectedException

**Comment by tomaarsen** [comment] 2022-09-01 09:56
Didn't mean to auto-close this through #3039. Let's not get ahead of ourselves, shall we? 😄

**Comment by tomaarsen** [comment] 2022-09-01 10:43
> https://github.com/nltk/nltk/issues/2989#issuecomment-1229963737

@Madnex I can't reproduce this. If I use:
```python
class HunposTagger(TaggerI):
    """
    A class for pos tagging with HunPos. The input is the paths to:
     - a model trained on training data
     - (optionally) the path to the hunpos-tag binary
     - (optionally) the encoding of the training data (default: ISO-8859-1)

    Check for available files
        >>> from nltk.test.hunpos_fixt import setup_module
        >>> setup_module()

    Example:
        ...
    """
```
and
```python
# nltk/test/hunpos_fixt.py
def setup_module():
    import pytest

    from nltk.tag.hunpos import HunposTagger

    try:
        tagger = HunposTagger('en_wsj.model')
    except (AssertionError, LookupError) as e:
        pytest.skip("Hunpos file is not available so hunpos doctest was skipped")
``` 
And then run `pytest --doctest-modules --doctest-continue-on-failure .\nltk\tag\hunpos.py` as suggested by @ekaf, then I get:
```
===================================================================================== test session starts =====================================================================================
platform win32 -- Python 3.9.4, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: C:\GitHub\nltk
plugins: cov-2.12.1, forked-1.3.0, mock-3.6.1, xdist-2.4.0
collected 1 item

nltk\tag\hunpos.py s                                                                                                                                                                     [100%] 

===================================================================================== 1 skipped in 1.16s ======================================================================================
```

And if I remove the `setup_module()`, then I get an `F` with a handful of errors.

**Comment by ekaf** [comment] 2022-09-01 16:56
I guess it will take several PRs before this issue is closed :) 

The list of errors is rather long, so it seems better to reduce it in small steps, with separate PRs. 

@Madnex, you mentioned earlier having "managed to fix most of the tests" (https://github.com/nltk/nltk/issues/2989#issuecomment-1222006897). Would you consider submitting some of those fixes, in order to eventually reduce the list of test failures?

**Comment by Madnex** [comment] 2022-09-05 06:47
> https://github.com/nltk/nltk/issues/2989#issuecomment-1234094779

Thanks @tomaarsen for the detailed explanation. In fact that is exactly what I also tried, however I always used `python -m doctest nltk/tag/hunpos.py` where it continued to fail. 

When I run `pytest --doctest-modules --doctest-continue-on-failure .\nltk\tag\hunpos.py` as suggested it is working as expected 👍 


> I guess it will take several PRs before this issue is closed :)
> 
> The list of errors is rather long, so it seems better to reduce it in small steps, with separate PRs.
> 
> @Madnex, you mentioned earlier having "managed to fix most of the tests" ([#2989 (comment)](https://github.com/nltk/nltk/issues/2989#issuecomment-1222006897)). Would you consider submitting some of those fixes, in order to eventually reduce the list of test failures?

@ekaf I will prepare a PR with the fixes I did so far :)

**Comment by Madnex** [comment] 2022-09-12 14:29
#3050 Added the PR. Let me know if something needs to be changed :)

**Comment by ekaf** [comment] 2022-09-22 10:00
After #3050, according to https://github.com/nltk/nltk/pull/3050#issuecomment-1253699492, only 10 tests in 5 files are now failing. And testing locally, I even see one failure less, since _nltk/parse/transitionparser.py:: nltk.parse.transitionparser.demo_ succeeds here.
Closing this issue is now within reach... 
Thanks @Madnex and @tomaarsen , I didn't expect that we would reach this point so quickly.

**Comment by tomaarsen** [comment] 2022-09-22 10:03
For reference, I've started working on the last remaining tests.
* I've fixed a bug in `nltk/tokenize/punkt.py::nltk.tokenize.punkt.PunktSentenceTokenizer._match_potential_end_contexts` that caused a test failure.
* I've ensured that the `nltk/parse/transitionparser.py::nltk.parse.transitionparser.demo` test won't fail. (It's trying to delete a file that is still open).
* I've updated all of the CoreNLP doctests to work as long as java and the CoreNLP files exist on the local machine. I'm still figuring out how to conditionally skip these. The new `check_binary` doesn't quite work I believe, as I need to check for jars.

**Comment by ekaf** [comment] 2022-09-22 11:32
I looked at the first failure, which is odd because it fails with pytest, but succeeds with python -m doctest:
```

__________________ [doctest] nltk.text.Text.collocation_list ___________________
410 
411         Return collocations derived from the text, ignoring stopwords.
412 
413             >>> from nltk.book import text4 # doctest: +NORMALIZE_WHITESPACE
Expected:
    *** Introductory Examples for the NLTK Book ***
    Loading text1, ..., text9 and sent1, ..., sent9
    Type the name of the text or sentence to view it.
    Type: 'texts()' or 'sents()' to list the materials.
    text1: Moby Dick by Herman Melville 1851
    text2: Sense and Sensibility by Jane Austen 1811
    text3: The Book of Genesis
    text4: Inaugural Address Corpus
    text5: Chat Corpus
    text6: Monty Python and the Holy Grail
    text7: Wall Street Journal
    text8: Personals Corpus
    text9: The Man Who Was Thursday by G . K . Chesterton 1908
Got nothing

[...]nltk/text.py:413: DocTestFailure
```


The failure is due to pytest ignoring the top-level print statements from the imported nltk/book.py. The easiest fix might be to delete the expected output, and just expect nothing.

**Comment by ekaf** [comment] 2022-09-28 12:27
This issue started as a quite remote, and not so realistic goal. But now, it seems that #3054 can really close it!

**Closed as completed** 2022-10-04 07:04 UTC
Labels: good first issue, tests, CI
