### ISSUE TITLE
Unable to use word_tokenize function 

### ISSUE THREAD

**Issue by beingEniola** [nltk/nltk#3324] opened 2024-09-13 14:34 UTC
This is my first time working on an NLP project, I'm unable to use the word_tokenize function which throws an error.

 after trying this code to solve the error 
      import nltk
      nltk.download('punkt')
      nltk.download('stopwords')  
      
The code above also throws an error.  How do I solve this,  an image is attached below.
![Screenshot 2024-09-13 152742](https://github.com/user-attachments/assets/22f00b37-69e9-4144-9d73-903e00667601)

**Comment by MohanedMashaly** [comment] 2024-09-14 17:43
Hi @beingEniola 

Can you provide more details on this error, to be able to help here,  there might be an  issue with Jupyter notebook  itself, so try to reproduce the same error on your IDLE or terminal.

**Comment by beingEniola** [comment] 2024-09-16 06:23
HI @MohanedMashaly 
Thank you for responding, it  still returns the same error
 
 "[nltk_data] Error loading popular: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>"   and also an output which says " False" 

I have attached a screenshot of when I ran it on my IDLE and terminal below 

![Screenshot 2024-09-16 072003](https://github.com/user-attachments/assets/439e6fd6-2ca4-4659-af5a-e2c82b67f66e)
![Screenshot 2024-09-16 072030](https://github.com/user-attachments/assets/228b49ff-25c0-4375-9336-f8afed753df7)

**Comment by ryanamannion** [comment] 2024-09-18 03:25
Hey @beingEniola can you try some of these steps from #3120 and see if any help? https://github.com/nltk/nltk/issues/3120#issuecomment-1422856621

More details here as well https://github.com/nltk/nltk/issues/3146

**Comment by ekaf** [comment] 2024-09-25 06:38
Duplicate of #3120

**Closed as completed by ekaf** 2024-09-25 06:38 UTC
