### ISSUE TITLE
Import Prolog parse tree into ntlk.Tree

### ISSUE THREAD

**Issue by LuigiCerone** [nltk/nltk#2194] opened 2018-11-29 10:47 UTC
Hi, is it possible to import into nltk.Tree a parse tree generate by using Prolog parsing with DCG predicate?
I've the following parse tree obtained by a prolog script I've written:

```
?- sentence(ParseTree, [the, block, b, is, blue],[]).
ParseTree = sentence(assertion(subject_phrase(determiner(the), noun(block), name(b)), verb_phrase(verb(is)), complement_phrase(adjective(blue)))) .

```
I've created another project  that does the same thing but with nltk library and if I insert the sentence ("the block b is blue") I get the following parse tree:

```
(A
  (SP (Det the) (Noun block) (Name b))
  (VP (V is))
  (CP (MP (Adj blue))))
```

Is there a way that I can use to import tree like `nltk.Tree.fromstring(parse_tree_in_prolog)`?
Thanks.

**Comment by alvations** [comment] 2018-12-17 16:14
I looks like the output of from your parser in prolog follows the standard bracketed parse format, so you should be able to use:

```python

parse_tree_in_prolog = """(A
  (SP (Det the) (Noun block) (Name b))
  (VP (V is))
  (CP (MP (Adj blue))))"""

Tree.fromstring(parse_tree_in_prolog)
```

[out]:

![](https://ibin.co/4QKVmaKGdV2g.png)

**Comment by LuigiCerone** [comment] 2018-12-18 11:04
Hi, thanks for your reply but I have misunderstood the question. 
The variable `parse_tree_in_prolog` isn't the one you posted, it's this one:

`parse_tree_in_prolog = sentence(assertion(subject_phrase(determiner(the), noun(block), name(b)), verb_phrase(verb(is)), complement_phrase(adjective(blue)))) .`

The other tree (the one you posted) is valid and it's generated by using nltk library, I asked for a way to convert my version of variable `parse_tree_in_prolog` to the one you posted.

**Comment by alvations** [comment] 2018-12-18 15:38
Ah, the prolog tree do still look like the bracketed parse ;P

```python
from nltk import Tree

prolog_tree_str = """sentence(assertion(subject_phrase(determiner(the), noun(block), name(b)), verb_phrase(verb(is)), complement_phrase(adjective(blue))))"""

Tree.fromstring("({})".format(prolog_tree_str))
```

[out]:

![](https://ibin.co/4QRM0SQM20P1.png)

**Comment by alvations** [comment] 2019-05-07 05:29
Closing issue as resolved if there's no further problems/enquiries =)

Please re-open if the issue is still relevant/unresolved.

**Closed as completed by alvations** 2019-05-07 05:29 UTC
Labels: parsing, resolved

**Comment by gsitaraman** [comment] 2020-04-21 19:53
The hierarchy is messed up in the tree
