### ISSUE TITLE
Get raw sentences

### ISSUE THREAD

**Issue by rpinquie** [nltk/nltk#2234] opened 2019-02-14 11:09 UTC
How can I get a list of raw sentences from a piece of text after using sentence splitting 'ssplit' ?

**Comment by alvations** [comment] 2019-05-07 03:33
There's no `ssplit` function in NLTK. Please do take a look at https://www.nltk.org/book/ch03.html

E.g.

```python
import nltk
from nltk import sent_tokenize

nltk.download('popular', quiet=True)

text = "This is a string with multiple sentences. Yes there are two sentences."
sent_tokenize(text)
```

**Comment by alvations** [comment] 2019-05-07 05:25
Closing issue as resolved. Please re-open if the issue is still relevant/unresolved.

**Closed as completed by alvations** 2019-05-07 05:25 UTC
Labels: documentation, tokenizer, resolved
