### ISSUE TITLE
Why the same content, but the low score?

### ISSUE THREAD

**Issue by youngzhou97qz** [nltk/nltk#2217] opened 2019-01-23 03:40 UTC
I tried to run the code as follow:

```
from nltk.translate.bleu_score import SmoothingFunction, sentence_bleu
sentence_bleu([['left', 'right']], ['left', 'right'], smoothing_function=cc.method0)
```
```
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  the n-gram count for each individual precision score would be:
/home/yzhou/anaconda3/lib/python3.6/site-packages/nltk/translate/bleu_score.py:503: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  the n-gram count for each individual precision score would be:
1.491668146240062e-154
```

I wonder why the BLEU score is so low, and how can I change the score to 1?

**Comment by alvations** [comment] 2019-05-03 16:10
@youngzhou97qz Thanks for raising the issue.

As the warning suggests, the scores for BLEU isn't stable once there's not at least one 4-gram matches between the reference and the hypothesis.

Previously 3.2 had non-traditional BLEU techniques that mitigates such problem by backing off to the largest n-gram matches but #1844 changed the BLEU to traditional BLEU score that matches that of Mosesdecoder.

**Comment by alvations** [comment] 2019-05-07 05:25
Closing issue as resolved. Please re-open if the issue is still relevant/unresolved.

**Closed as completed by alvations** 2019-05-07 05:25 UTC
Labels: SMT, resolved

**Comment by youngzhou97qz** [comment] 2019-05-07 06:46
> @youngzhou97qz Thanks for raising the issue.
> 
> As the warning suggests, the scores for BLEU isn't stable once there's not at least one 4-gram matches between the reference and the hypothesis.
> 
> Previously 3.2 had non-traditional BLEU techniques that mitigates such problem by backing off to the largest n-gram matches but #1844 changed the BLEU to traditional BLEU score that matches that of Mosesdecoder.

Thank you very much for your explanation!
