### ISSUE TITLE
HMM tagger bug

### ISSUE THREAD

**Issue by alexrudnick** [nltk/nltk#69] opened 2012-01-17 06:25 UTC
$ python nltk/tag/hmm.py

[...]

HMM-tagged: the/AT grand/DO jury/DO commented/DO on/DO a/DO number/DO of/DO
other/DO topics/DO ,/DO among/DO them/DO the/DO atlanta/DO and/DO fulton/DO
county/DO purchasing/DO departments/DO which/DO it/DO said/DO ``/DO are/DO
well/DO operated/DO and/DO follow/DO generally/DO accepted/DO practices/DO
which/DO inure/DO to/DO the/DO best/DO interest/DO of/DO both/DO
governments/DO ''/DO ./DO

All demo cases tag words as &quot;DO&quot; after the first word.

<p>Migrated from http://code.google.com/p/nltk/issues/detail?id=393</p><hr/><h2>earlier comments</h2>
<p><strong>alex.rudnick said, at 2010-01-08T15:59:35.000Z:</strong></p>

<p>Just the demo cases in demo_pos_bw(), though, right? All the other demos in that file 
return sensible-looking results, for me.

Baum-Welch can take a really long time to train up a good HMM; isn't doing 5 
iterations with 10 sample sentences likely to produce wonky results?</p><p><strong>aku.ankka8 said, at 2010-02-19T23:57:42.000Z:</strong></p>

I did this:

```
>>> import nltk
>>> BROWN = list(nltk.corpus.brown.tagged_sents())
>>> train = BROWN[:51606]
>>> test = BROWN[51606:]
>>> hmmt = nltk.tag.HiddenMarkovModelTrainer()
>>> hmm = hmmt.train(train)
>>> hmm.evaluate(test)
0.67956455229353951
>>> hmm.tag([x[0] for x in test[10]])
[('Had', 'HVD'), ('Dandy', 'NP'), ('been', 'BEN'), ('older', 'JJR'), ('or', 'CC'),
('wiser', 'JJR'), (',', ','), ('instinct', 'NN'), ('might', 'MD'), ('have', 'HV'),
('warned', 'VBN'), ('him', 'PPO'), ('that', 'CS'), ('he', 'PPS'), ('would', 'MD'),
('be', 'BE'), ('well', 'RB'), ('advised', 'VBN'), ('to', 'IN'), ('flee', 'AT'),
('from', 'AT'), ('the', 'AT'), ("Lalauries'", 'AT'), ('tender', 'AT'), ('care',
'AT'), ('if', 'AT'), ('he', 'AT'), ('valued', 'AT'), ('his', 'AT'), ('life', 'AT'),
('.', 'AT')]
```

I guess I'm doing something wrong, but haven't figured out what ... this is on 2.0b6,
but I got very similar results with 2.0b8 as well.

**Comment by kmike** [comment] 2013-03-20 13:11
This is not directly related to Baum-Welch; the issue is caused by using default MLEProbDist estimator which doesn't handle missing words itself. So the code should either use an another estimator or somehow handle missing words otherwise (e.g. by replacing them with a special token). 

```
>>> import nltk
>>> from nltk.probability import LidstoneProbDist
>>> BROWN = list(nltk.corpus.brown.tagged_sents())
>>> train = BROWN[:51606]
>>> test = BROWN[51606:51700]  # model.evalute is so slow..
>>> estimator = estimator=lambda fd, bins: LidstoneProbDist(fd, 0.1, bins)
>>> hmmt = nltk.tag.HiddenMarkovModelTrainer()
>>> hmm = hmmt.train(train)
>>> hmm.evaluate(test)
0.9265283230510376
>>> hmm.tag([x[0] for x in test[10]])
[(u'Had', u'PPS'),
 (u'Dandy', u'HVD'),
 (u'been', u'BEN'),
 (u'older', u'JJR'),
 (u'or', u'CC'),
 (u'wiser', u'JJR'),
 (u',', u','),
 (u'instinct', u'NN'),
 (u'might', u'MD'),
 (u'have', u'HV'),
 (u'warned', u'VBN'),
 (u'him', u'PPO'),
 (u'that', u'CS'),
 (u'he', u'PPS'),
 (u'would', u'MD'),
 (u'be', u'BE'),
 (u'well', u'RB'),
 (u'advised', u'VBN'),
 (u'to', u'TO'),
 (u'flee', u'VB'),
 (u'from', u'IN'),
 (u'the', u'AT'),
 (u"Lalauries'", u'QL'),
 (u'tender', u'JJ'),
 (u'care', u'NN'),
 (u'if', u'CS'),
 (u'he', u'PPS'),
 (u'valued', u'VBD'),
 (u'his', u'PP$'),
 (u'life', u'NN'),
 (u'.', u'.')]
```

What we can do is change the default estimator for HMM or write better docs; HMM code works as expected.

---

By the way, Baum-Welch demo doesn't work good for a similar reason: HiddenMarkovModelTrainer.train_unsupervised always uses DictionaryConditionalProbDist and MutableProbDist, even if initial model used an another ProbDist.

That's why demo_pos_bw() performs so bad - it is not because there are too few iterations or too few training examples. Baum-Welch in demo_pos_bw() is applied to a pre-trained model that tags the sequence much better, but replacing model's ProbDist with a "simpler" one (plus other serious bugs, some of them which are fixed in #371 ) destroys the quality and makes HiddenMarkovModelTrainer.train_unsupervised unusable.

**Comment by kmike** [comment] 2013-03-20 13:39
...I was not preciese - in demo functions precomputed symbols and states are passed to HiddenMarkovModelTrainer constructor so there shouldn't be unknown words - but there could be unseen transitions, and smoothing could help even if all words are known.

**Comment by prisawant** [comment] 2017-07-10 10:10
I am trying to train HMM on unsupervised data using model trained on supervised data. But because train_unsupervised model uses DictionaryConditionalProbDist for symbols which are unseen I get forward probability as `inf` in Baum-Welch. Can anyone tell workaround for this or how to specify smoothing in train_unsupervised

**Comment by alvations** [comment] 2017-10-14 14:58
c.f. #428

**Closed as completed** 2017-12-23 01:47 UTC
Labels: tagger

**Comment by Hyperparticle** [comment] 2018-03-10 22:01
I am also trying to train an HMM on unsupervised data, first training with supervised data.  I can apply smoothing in the supervised training via the `estimator` parameter, but there is no simple way to smooth the result of the unsupervised training, as the transitions and outputs erase the underlying `FreqDist` used to calculate smoothing.

Without smoothing, both supervised and unsupervised evaluation get very low accuracies. Is there a way to apply any sort of smoothing to alleviate this?

**Comment by Anam-tahir** [comment] 2018-09-15 20:12
> This is not directly related to Baum-Welch; the issue is caused by using default MLEProbDist estimator which doesn't handle missing words itself. So the code should either use an another estimator or somehow handle missing words otherwise (e.g. by replacing them with a special token).
> 
> ```
> >>> import nltk
> >>> from nltk.probability import LidstoneProbDist
> >>> BROWN = list(nltk.corpus.brown.tagged_sents())
> >>> train = BROWN[:51606]
> >>> test = BROWN[51606:51700]  # model.evalute is so slow..
> >>> estimator = estimator=lambda fd, bins: LidstoneProbDist(fd, 0.1, bins)
> >>> hmmt = nltk.tag.HiddenMarkovModelTrainer()
> >>> hmm = hmmt.train(train)
> >>> hmm.evaluate(test)
> 0.9265283230510376
> >>> hmm.tag([x[0] for x in test[10]])
> [(u'Had', u'PPS'),
>  (u'Dandy', u'HVD'),
>  (u'been', u'BEN'),
>  (u'older', u'JJR'),
>  (u'or', u'CC'),
>  (u'wiser', u'JJR'),
>  (u',', u','),
>  (u'instinct', u'NN'),
>  (u'might', u'MD'),
>  (u'have', u'HV'),
>  (u'warned', u'VBN'),
>  (u'him', u'PPO'),
>  (u'that', u'CS'),
>  (u'he', u'PPS'),
>  (u'would', u'MD'),
>  (u'be', u'BE'),
>  (u'well', u'RB'),
>  (u'advised', u'VBN'),
>  (u'to', u'TO'),
>  (u'flee', u'VB'),
>  (u'from', u'IN'),
>  (u'the', u'AT'),
>  (u"Lalauries'", u'QL'),
>  (u'tender', u'JJ'),
>  (u'care', u'NN'),
>  (u'if', u'CS'),
>  (u'he', u'PPS'),
>  (u'valued', u'VBD'),
>  (u'his', u'PP$'),
>  (u'life', u'NN'),
>  (u'.', u'.')]
> ```
> What we can do is change the default estimator for HMM or write better docs; HMM code works as expected.
> 
> By the way, Baum-Welch demo doesn't work good for a similar reason: HiddenMarkovModelTrainer.train_unsupervised always uses DictionaryConditionalProbDist and MutableProbDist, even if initial model used an another ProbDist.
> 
> That's why demo_pos_bw() performs so bad - it is not because there are too few iterations or too few training examples. Baum-Welch in demo_pos_bw() is applied to a pre-trained model that tags the sequence much better, but replacing model's ProbDist with a "simpler" one (plus other serious bugs, some of them which are fixed in #371 ) destroys the quality and makes HiddenMarkovModelTrainer.train_unsupervised unusable.

Myexample is:
import nltk
# from nltk.tag import hmm
train = [[('ابوظہبی','NEL'),('سوائی','NEP'),('محمد','NEP'), ('مہاراجہ','NED'), ('ہندوستان','NEL'), ('لوہا','NEO'), ('ایف آئی اے','NEA')],[('لینس','NEB'),('ڈاکٹر','NETP'),('سماجی ترقیاتی تنظیم','NETO'),('73ء','NETI '),('ایک','NEN '),('بارہ صدیاں','NEM '),('اسلام','NETE ')]]

test = ([['ایف آئی اے','ڈاکٹر',"ہندوستان",'مہاراجہ'], ['ایلبیٹ رس','پلان کولمبیہ','پانچ']])
estimator=lambda fd, bins: LidstoneProbDist(fd, 0.1, bins)
hmmt = nltk.tag.HiddenMarkovModelTrainer()
hmm = hmmt.train_supervised(train)
# hmm.evaluate(test)
print(hmm.tag([x[0] for x in test[0:]]))
Ouput: [('ایف آئی اے', 'NEL'), ('ایلبیٹ رس', 'NEL')]

How can i fix it :( ?

**Comment by Anam-tahir** [comment] 2018-09-15 20:13
@kmike  please solve my problem asap

**Comment by TeemuKoivisto** [comment] 2020-02-06 09:19
Hi, I think this is a bug that still exists. So what happens is that for every unknown word the semi-supervised model encounters it suddenly stops predicting the next POS tags and just keeps repeating the previous tag: 
```py
[('Yesterday', 'RB'),
 ('these', 'JJR'),
 ('fiends', 'DT'),
 ('operated', 'DT'),
 ('upon', 'DT'),
 ('Doggo', 'DT'),
 ('.', 'DT')]
```

So anyway, there's a quick fix with monkey-patching the _output_logprob method to instead of returning infinity when an unknown word is encountered, to return its prior. I think that is a lot saner default, don't you agree?

```py
def _output_logprob(self, state, symbol):
    """
    :return: the log probability of the symbol being observed in the given
        state
    :rtype: float
    """
    logprob = self._outputs[state].logprob(symbol)
    if logprob == -np.inf:
        return self._priors.logprob(state)
    return logprob

hmm = trainer.train_supervised(labeled_sents, estimator=lambda fd,bins: LidstoneProbDist(fd, 0.1, bins))
hmm._output_logprob = _output_logprob.__get__(hmm, HiddenMarkovModelTagger)
hmm = trainer.train_unsupervised(
    unlabeled_sents, model=hmm, max_iterations=max_iterations, verbose=True
)
```
I'm not sure mathematically what is the correct way here, but if the prior is the non-zero smoothed probability that you give to all the words no matter what they are, and the `self._outputs[state].logprob(symbol)` is just getting the probability value by its symbol, which in often times doesn't exist, I think this is about right.

If there's no tests to be fixed I can create a PR. @alexrudnick @kmike
