### ISSUE TITLE
data.doctest fails

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#446] opened 2013-07-17 10:28 UTC
data.doctest started failing after merging #441 with the following exceptions:

```
======================================================================
FAIL: Doctest: data.doctest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for data.doctest
  File "/Users/kmike/svn/nltk/nltk/test/data.doctest", line 0

----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/data.doctest", line 44, in data.doctest
Failed example:
    print(nltk.data.load(url)) # doctest: +ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest data.doctest[7]>", line 1, in <module>
        print(nltk.data.load(url)) # doctest: +ELLIPSIS
      File "/Users/kmike/svn/nltk/nltk/data.py", line 690, in load
        opened_resource = _open(resource_url)
      File "/Users/kmike/svn/nltk/nltk/data.py", line 798, in _open
        return find(_path, ['']).open()
      File "/Users/kmike/svn/nltk/nltk/data.py", line 537, in find
        raise LookupError(resource_not_found)
    LookupError: 
    **********************************************************************
      Resource
      u'Users/kmike/nltk_data/grammars/sample_grammars/toy.cfg' not
      found.  Please use the NLTK Downloader to obtain the resource:
      >>> nltk.download()
      Searched in:
        - u''
    **********************************************************************
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/data.doctest", line 277, in data.doctest
Failed example:
    for i, url in enumerate(urls):
        nltk.data.retrieve(url, 'toy-%d.cfg' % i) # doctest: +ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest data.doctest[52]>", line 2, in <module>
        nltk.data.retrieve(url, 'toy-%d.cfg' % i) # doctest: +ELLIPSIS
      File "/Users/kmike/svn/nltk/nltk/data.py", line 564, in retrieve
        infile = _open(resource_url)
      File "/Users/kmike/svn/nltk/nltk/data.py", line 798, in _open
        return find(_path, ['']).open()
      File "/Users/kmike/svn/nltk/nltk/data.py", line 537, in find
        raise LookupError(resource_not_found)
    LookupError: 
    **********************************************************************
      Resource
      u'Users/kmike/nltk_data/grammars/sample_grammars/toy.cfg' not
      found.  Please use the NLTK Downloader to obtain the resource:
      >>> nltk.download()
      Searched in:
        - u''
    **********************************************************************


----------------------------------------------------------------------
Ran 1 test in 0.857s
```

File `/Users/kmike/nltk_data/grammars/sample_grammars/toy.cfg` exists.

**Comment by stevenxxiu** [comment] 2013-07-18 14:53
I've fixed this on my branch.

**Comment by stevenxxiu** [comment] 2013-07-22 11:25
They should be merged now

**Comment by stevenbird** [comment] 2013-07-22 11:51
It looks like the problem is fixed.

**Closed as completed by stevenbird** 2013-07-22 11:51 UTC
