### ISSUE TITLE
False reporting missing dependency scikit-learn

### ISSUE THREAD

**Issue by PanderMusubi** [nltk/nltk#498] opened 2013-10-01 05:22 UTC
With version 3.0a2 2013-07-12 the following is reported:

```
/usr/local/lib/python2.7/dist-packages/nltk-3.0a2-py2.7.egg/nltk/classify/scikitlearn.py:44: UserWarning: scikit-learn is not installed. Try 'pip install scikit-learn'.
```

  warn("scikit-learn is not installed."

even though scikit-learn is installed via apt-get on Ubuntu 13.04 or via pip. Please fox this.

When scikit-learn is not installed, it is also reported but this is very annoying. Either make it a hard dependency or do not report on it because reporting it each time one uses nltk is very annoying.

**Comment by stevenbird** [comment] 2013-10-03 23:49
@larsmans would you please take a look at this?

**Comment by larsmans** [comment] 2013-10-04 09:50
@PanderMusubi Cannot reproduce. Does `import sklearn` work in a Python 2.7 shell?

**Comment by stevenbird** [comment] 2013-10-04 11:07
I get the error in Python 3.2:

$ cd nltk/nltk/test
$ python runtests.py align.doctest
/Users/sb/git/nltk/nltk/classify/scikitlearn.py:44: UserWarning: scikit-learn is not installed. Try 'pip install scikit-learn'.
  warn("scikit-learn is not installed."

scikit-learn isn't installed in this instance, but there must be some cascading imports that cause the classifiers to be imported.

NB it might be worth looking at how we deal with the optional numpy dependency (see, e.g. tag/hmm.py), where we ignore the ImportError, and if someone uses the module it will result in an error at runtime.

**Comment by kmike** [comment] 2013-10-04 17:49
I think that warning is issued in Ubuntu 13.04 if scikit-learn is installed via apt-get because Ubuntu 13.04 provides scikit-learn 0.11, and LabelEncoder was introduced in scikit-learn 0.12.

**Comment by adonoho** [comment] 2013-10-04 21:03
Confirming Steven Bird's report on OS X 10.8.5, Python 3.3.2 pulled from the latest master commit.

```
astraeus:test awd$ python3 runtests.py align.doctest
/Users/awd/Projects/Python/NLTK/nltk/nltk/classify/scikitlearn.py:44: UserWarning: scikit-learn is not installed. Try 'pip install scikit-learn'.
warn("scikit-learn is not installed."
.
----------------------------------------------------------------------
Ran 1 test in 5.061s

OK
```

scikit was installed via, IIRC, pip.

Andrew

**Comment by PanderMusubi** [comment] 2013-10-05 12:33
see below, at the moment no scikit-learn installed

```
$ python
Python 2.7.4 (default, Sep 26 2013, 03:20:26) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named sklearn
```

**Comment by stevenbird** [comment] 2013-10-17 22:46
I intend to do a conditional import of sklearn to avoid this error message. Users without sklearn installed would only see an error when they ran code that required sklearn.

**Comment by stevenbird** [comment] 2013-10-19 06:36
Resolved in https://github.com/nltk/nltk/commit/03fbcdfd4ed5e012c8835e92dff46c684ea5c653

**Closed as completed by stevenbird** 2013-10-19 06:36 UTC
