### ISSUE TITLE
issue with nltk import , VS code

### ISSUE THREAD

**Issue by harshith001** [nltk/nltk#2943] opened 2022-02-01 13:52 UTC
PS D:\Sem 2\PFA\Programs PFA> & C:/Users/bhars/anaconda3/python.exe "d:/Sem 2/PFA/Programs PFA/nltk.py"
Traceback (most recent call last):
  File "d:\Sem 2\PFA\Programs PFA\nltk.py", line 2, in <module>
    import nltk
  File "d:\Sem 2\PFA\Programs PFA\nltk.py", line 6, in <module>
    nltk_tokens = nltk.word_tokenize(word_data)
AttributeError: partially initialized module 'nltk' has no attribute 'word_tokenize' (most likely due to a circular import)

**Comment by tomaarsen** [comment] 2022-02-01 14:12
Hello!

This problem is caused by is a tricky issue in Python that occurs whenever you name one of your files the same thing as one of the modules you want to import. Let me show you.

Imagine I have a file called `this_is_my_file.py`, which has only one line, and looks like this:
```python
from this_is_my_file import something
```
If I then run it, then I'll get this output:
```
Traceback (most recent call last):
  File "[sic]\this_is_my_file.py", line 1, in <module>
    from this_is_my_file import something
  File "[sic]\this_is_my_file.py", line 1, in <module>
    from this_is_my_file import something
ImportError: cannot import name 'something' from partially initialized module 'this_is_my_file' (most likely due to a circular import) ([sic]\this_is_my_file.py)
```
Although somewhat confusing if you didn't see it coming, this issue is somewhat logical. Rather than importing from some module, `nltk` in your example, Python will now try to import from your local file `nltk.py`. However, that will of course cause a circular import: `nltk.py` tries to import `word_tokenize` from `nltk.py`, i.e. itself.

So, your issue should disappear once you rename `nltk.py` to something else. In Python, it is recommended to not give your files the same name as one of the modules that you might use.

I think that should resolve the issue, so I'll close this now.

**Closed as completed by tomaarsen** 2022-02-01 14:12 UTC
