### ISSUE TITLE
regex package version  2021.10.8 not working

### ISSUE THREAD

**Issue by patialashahi31** [nltk/nltk#2857] opened 2021-10-15 16:24 UTC
While importing nltk it gives error on macbook M1 , python version 3.9.7

```
dlopen(/venv/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	t/venv/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so: code signature in (/venv/lib/python3.9/site-packages/regex/_regex.cpython-39-darwin.so) not valid for use in process using Library Validation: Trying to load an unsigned lib
```
	
	
After degrading regex package version to 2021.8.3 it works fine

**Comment by purificant** [comment] 2021-10-15 16:51
Unable to reproduce on Linux. CI pipeline is passing for nltk with regex 2021.10.8 on Mac: https://github.com/nltk/nltk/runs/3905881265?check_suite_focus=true using latest version of regex as per: https://github.com/nltk/nltk/blob/develop/requirements-ci.txt

```bash
python --version
Python 3.9.7

pip freeze
click==8.0.3
joblib==1.1.0
nltk==3.6.5
regex==2021.10.8
tqdm==4.62.3

python
Python 3.9.7 (default, Sep  6 2021, 09:03:12) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.__version__
'3.6.5'
```

**Comment by purificant** [comment] 2021-10-15 16:54
May I suggest creating a new virtual environment, installing nltk and then checking if you can import it in python?

**Comment by patialashahi31** [comment] 2021-10-16 04:57
Hi. I tried with virtualenv as well as pipenv 3-4 times. 
Also can be it Mac M1 specific?

**Comment by purificant** [comment] 2021-10-17 07:31
Are you able to `pip install regex==2021.10.8` and `pip install nltk==3.6.5`?

**Comment by patialashahi31** [comment] 2021-10-17 09:33
yes

**Comment by purificant** [comment] 2021-10-17 18:53
Can you share the output log when you start python interpreter and then
```python
>>> import nltk
>>> nltk.__version__
```
and 

```python
>>> import regex
>>> regex.compile(r"([^a-zA-Z0-9])\1{3,}")
```

**Comment by amateur-dev** [comment] 2021-11-05 03:06
I am not able to get this done
```
>>> import regex
>>> regex.compile(r"([^a-zA-Z0-9])\1{3,}")
```

Same error:

```/opt/homebrew/lib/python3.10/site-packages/regex/_regex.cpython-310-darwin.so: code signature in (/opt/homebrew/lib/python3.10/site-packages/regex/_regex.cpython-310-darwin.so) not valid for use in process using Library Validation: Trying to load an unsigned library```

**Comment by purificant** [comment] 2021-11-05 08:13
@amateur-dev 
It looks like there's an issue with `regex` package on macOS. Please try `pip install --upgrade regex`.
It is worth checking if this issue is resolved in the latest(2021.11.2) release of `regex` package. If not, please raise an issue with the package maintainers: https://pypi.org/project/regex/

**Comment by tomaarsen** [comment] 2022-12-13 21:49
I believe this should be handled now.

**Closed as completed by tomaarsen** 2022-12-13 21:49 UTC

**Comment by Dimble-Scaria** [comment] 2023-11-02 17:03
Does regex==2021.8.3  work with tiktoken
