### ISSUE TITLE
nltk.word_tokenize() (Treebank Tokenizer) tokenize double quotes into 2 backticks

### ISSUE THREAD

**Issue by BLKSerene** [nltk/nltk#2140] opened 2018-10-12 15:47 UTC
```
>>> nltk.word_tokenize('"')
['``']
```

So, is this the expected behavior?

And is it OK to use the Treebank tokenizer on languages other than English? (Maybe all Indo-European languages?)

**Comment by alvations** [comment] 2018-10-24 07:14
That is the expected behavior of the Penn Treebank tokenizer than the `nltk.word_tokenize` is based on. Perhaps, we need to move faster in creating our own unique tokenizer and put away the PTB one.

**Comment by piero** [comment] 2019-03-19 13:54
I noticed that this behaviour is inconsistent, e.g. `"Here is a ''double quoted'' text"` is tokenized as `['Here', 'is', 'a', '``', 'double', 'quoted', "''", 'text']`.

Assuming that the second set of single quotes should also be converted into back-ticks, I've fixed this  in this PR: https://github.com/nltk/nltk/pull/2254

**Comment by alvations** [comment] 2019-03-19 23:10
The second set of single quotes should be kept as two single quotes. This `''` is to encode end of quotation and `` is to encode start of quotation, as per the documentation of Penn Treebank corpus.

**Comment by alvations** [comment] 2019-05-07 05:30
Closing issue as resolved. 

Please do re-open if the issue is there's a push to change the tokenizer way in handling starting and ending quotations.

**Closed as completed by alvations** 2019-05-07 05:30 UTC
Labels: tokenizer, resolved
