### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by atlijas** [nltk/nltk#2523] opened 2020-03-30 00:18 UTC
When importing sent_tokenize from nltk.tokenize:

path/to/python3.7/dist-packages/nltk/decorators.py:68: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  regargs, varargs, varkwargs, defaults, formatvalue=lambda value: ""
path/to/python3.7/dist-packages/nltk/lm/counter.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Sequence, defaultdict
path/to/python3.7/dist-packages/nltk/lm/vocabulary.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Counter, Iterable

**Comment by tirkarthi** [comment] 2020-04-11 07:58
Seems like a duplicate of https://github.com/nltk/nltk/issues/2338

**Closed as completed** 2021-06-04 10:42 UTC
