### ISSUE TITLE
Bug in WordNet wup_similarity for same-synset comparisons

### ISSUE THREAD

**Issue by davidjurgens** [nltk/nltk#1030] opened 2015-06-29 18:04 UTC
The implementation of the Wu & Palmer similarity function WordNet seems to report an incorrect value when comparing a synset to itself.

``` python
from nltk.corpus import wordnet as wn
syn1 = wn.synset('bread.n.1')
syn1.wup_similarity(syn1) # yields 1.0 as expected
syn1 = wn.synset('dog.n.1')
syn1.wup_similarity(syn1) # yields 0.9285714285714286
```

For the second dog.n.1 comparison, [WordNet::Similarity](http://maraca.d.umn.edu/cgi-bin/similarity/similarity.cgi?word1=dog%23n%231&senses1=synset&word2=dog%23n%231&senses2=synset&measure=wup&rootnode=yes) gives the correct similarity of 1.0, as does [WS4J](http://ws4jdemo.appspot.com/?mode=w&s1=&w1=dog%23n%231&s2=&w2=dog%23n%231) (though the latter has its own bugs too)

I see the above results when using python 2.7.5,  NLTK 3.0.3, and WordNet 3.0

**Comment by stevenbird** [comment] 2015-07-21 16:32
Thanks @davidjurgens

**Comment by alvations** [comment] 2015-09-30 09:51
@stevenbird @davidjurgens I would think it's a feature and not a bug but i agree, it should be fixed. =)

This issue was also raised here: http://stackoverflow.com/questions/32333996/python-nltk-wup-similarity-score-not-unity-for-exact-same-word/32347253#32347253

The simple fix could have been at https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L861 but I'm not sure whether I can do the if statement to self. 

```
subsumer = self if self in subsumers else subsumers[0]
```

or maybe this is computationally cheaper at https://github.com/nltk/nltk/blob/develop/nltk/corpus/reader/wordnet.py#L855:

```
if self == other:
    subsumers = [self]
else:
    subsumers = self.lowest_common_hypernyms(other, simulate_root=simulate_root and need_root, use_min_depth=True)
```

**Closed as completed** 2017-08-16 23:25 UTC
Labels: good first issue, corpus, bug
