### ISSUE TITLE
Wordnet2021 won't load

### ISSUE THREAD

**Issue by alcinos** [nltk/nltk#3051] opened 2022-09-25 21:43 UTC
On a fresh install, this is what I did:

```
> import nltk
> nltk.__version__
'3.7'
> nltk.download('wordnet2021')
> nltk.download('omw-1.4')
> from nltk.corpus import wordnet2021 as wn
> wn.synsets("dog")
```
I get the following traceback:
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/data.py", line 403, in __init__
    zipfile.getinfo(entry)
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/zipfile.py", line 1439, in getinfo
    raise KeyError(
KeyError: "There is no item named 'wordnet/index.sense' in the archive"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/corpus/reader/wordnet.py", line 1201, in __init__
    self.map30 = self.map_wn30()
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/corpus/reader/wordnet.py", line 1226, in map_wn30
    sk1 = self.corpus2sk("wordnet")
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/corpus/reader/wordnet.py", line 1212, in corpus2sk
    with self.open(fn) as fp:
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/corpus/reader/api.py", line 231, in open
    stream = self._root.join(file).open(encoding)
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/data.py", line 451, in join
    return ZipFilePathPointer(self._zipfile, entry)
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/data.py", line 415, in __init__
    raise OSError(
OSError: Zipfile '/home/user/nltk_data/corpora/wordnet2021.zip' does not contain 'wordnet/index.sense'
```

This can be worked-around by removing the mapping to wn30, which I don't care about anyways. Specifically, I changed `nltk/corpus/reader/wordnet.py:1201` to 
```
self.map30 = None
``` 
which allows the error to go away and the library to be usable.

**Comment by tomaarsen** [comment] 2022-09-25 21:56
I'm sorry to hear that you had such issues with getting the library to work normally!

@ekaf do you have any idea what might be going on here? I know some other users in the past have had issues with `wordnet` not unzipping automatically like it should - perhaps that is related?

**Comment by ekaf** [comment] 2022-09-26 05:58
This looks like a problem that occurs when trying to use an alternative wordnet, like f. ex. _wordnet2021_, without also downloading the main _wordnet_ package.

When I reproduce it, I get an appropriate error message:
```
Traceback (most recent call last):
  File "nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet.zip/wordnet/
```
This message says that we look for the _wordnet/_ directory in _corpora/wordnet.zip_, but haven't downloaded that zipfile yet.

Curiously, @alcinos gets a different error message, induced by looking for 'wordnet/index.sense' in the wong zipfile, namely the downloaded _corpora/wordnet2021.zip_ (which only contains a _wordnet2021_ directory):
```
  File "/home/user/miniconda3/envs/test_env/lib/python3.10/site-packages/nltk/data.py", line 415, in __init__
    raise OSError(
OSError: Zipfile '/home/user/nltk_data/corpora/wordnet2021.zip' does not contain 'wordnet/index.sense'
```
This should not happen. I have no idea why @alcinos could be looking in the wrong zipfile.

The _wordnet/index.sense_ file from the plain _corpora/wordnet.zip_ package is used to construct a mapping between the loaded wordnet2021 and WordNet 3.0.
This mapping is necessary if you want to use the multilingual wordnets from OMW, since these are tied to WordNet 3.0 identifiers, but the mapping is not needed if you only use English.

After downloading  _wordnet.zip_, everything is ok:

```
>>>from nltk.corpus import wordnet2021 as wn
>>>print(wn.synsets("dog"))
```

> [Synset('dog.n.01'), Synset('frump.n.01'), Synset('dog.n.03'), Synset('cad.n.01'), Synset('frank.n.02'), Synset('pawl.n.01'), Synset('andiron.n.01'), Synset('chase.v.01')]

**Comment by alcinos** [comment] 2022-09-26 13:10
@ekaf Thanks for looking into it. I also tried downloading the regular wordnet to see if it fixes the issue for me, but it doesn't. 
I guess this is somewhat expected because `wordnet2021.zip` only contains a `wordnet2021` directory, so when it tries to look-up `wordnet` inside the zip it expectedly fails.

My guess is that there is some sort of logic mistake related to why it decides to look inside the zip in the first place. If it were to look in the already extracted files, as it seems to be doing for you, then it would find the wordnet directory.

To give more info on the repro, I installed miniconda on a machine that never had nltk installed (so no data anywhere), then created an env, pip installed nltk and ran the command from my first post. I was able to reproduce the bugs on two different machines.

**Comment by ekaf** [comment] 2022-09-26 18:16
@alcinos, you are completely right: with the standard nltk 3.7, I get exactly the same output as you. The reason why I got different results was because I used the updated version of wordnet.py from the _develop_ branch on github.

**Comment by ekaf** [comment] 2022-09-27 10:54
@alcinos, the newer _wordnet.py_ will be included in the next _nltk_ release. Until then, the workaround is to unzip the wordnet data packages in the _nltk_data/corpora_ directory.

**Comment by tomaarsen** [comment] 2022-12-13 21:39
This should be changed in the new NLTK 3.8!

Your script now results in:
```python
[Synset('dog.n.01'), Synset('frump.n.01'), Synset('dog.n.03'), Synset('cad.n.01'), Synset('frank.n.02'), Synset('pawl.n.01'), Synset('andiron.n.01'), Synset('chase.v.01')]
```

**Closed as completed by tomaarsen** 2022-12-13 21:39 UTC
Labels: bug, wordnet

**Comment by slokeshrestha26** [comment] 2023-05-16 02:00
Hello, 

So I tried the following with default wordnet (using `nltk.download("wordnet")`) installed. I entered the following commands and get the following errors:

```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.__version__
'3.8.1'
>>> from nltk.corpus import wordnet2022 as wn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'wordnet2022' from 'nltk.corpus' (/home/sloke/py_envs/llms_annotate/lib/python3.8/site-packages/nltk/corpus/__init__.py)
```

Edit: I forgot to say that I downloaded the data as well. The commands entered are as follows. Sorry for the confusion:

```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
nl>>> nltk.__version__
'3.8.1'
>>> nltk.download("wordnet2022")
[nltk_data] Downloading package wordnet2022 to
[nltk_data]     /home/sloke/nltk_data...
[nltk_data]   Package wordnet2022 is already up-to-date!
True
>>> from nltk.corpus import wordnet2022 as wn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'wordnet2022' from 'nltk.corpus' (/home/sloke/py_envs/llms_annotate/lib/python3.8/site-packages/nltk/corpus/__init__.py)
>>> 



```

**Comment by ekaf** [comment] 2023-05-16 07:19
@slokeshrestha26, you try to import the new "wordnet2022", but you have only installed the default "wordnet" data. 

You need to download the  "wordnet2022" data:

> LookupError: ********************************************************************** 
> Resource wordnet2022 not found.
> Please use the NLTK Downloader to obtain the resource: 
>>> import nltk 
>>> nltk.download('wordnet2022')

**Comment by slokeshrestha26** [comment] 2023-05-16 23:44
@ekaf, thank you for the reply. Sorry for the confusion. I did download the wordnet2022 data as well. 

I have updated the issue that reflects the download. 

Thank you, 
Sloke

**Comment by ekaf** [comment] 2023-05-17 04:32
@slokeshrestha26, wordnet2022 was only recently added to the 'develop' branch of NLTK on Github, and will first be supported in the next standard NLTK release. Maybe @tomaarsen knows more about this?

So it is not strange that you cannot import the name 'wordnet2022' from your copy of  'nltk/corpus/\_\_init\_\_.py'.  However it is defined at lines 409-413 in [the newer version on Github:](https://github.com/nltk/nltk/blob/develop/nltk/corpus/__init__.py)

```
wordnet2022: WordNetCorpusReader = LazyCorpusLoader(
    "wordnet2022",
    WordNetCorpusReader,
    LazyCorpusLoader("omw-1.4", CorpusReader, r".*/wn-data-.*\.tab", encoding="utf8"),
)
```

**Comment by tomaarsen** [comment] 2023-05-17 21:21
My apologies. In the meantime, you can use the development branch version of NLTK:
```
pip install git+https://github.com/nltk/nltk.git
```
Indeed, Wordnet 2022 hasn't been released in a NLTK version yet - I had not realised this.
