### ISSUE TITLE
FrameNet: Subcorpus name with non-ascii character can't be handled

### ISSUE THREAD

**Issue by rleegoldman** [nltk/nltk#993] opened 2015-05-28 17:43 UTC
This is probably an issue with the underlying xml reader, but here are the repro steps:

```
from nltk.corpus import framenet as fn
minimum = fn.lu(14294)
id = minimum.ID  # okay
sc = minimum.subCorpus  # throws UnicodeDecodeError
```

Looks like one of the elements in the xml file is `<subCorpus name="01-£10,000-(1)"/>`

**Comment by nschneid** [comment] 2015-05-29 01:10
I think this will be fixed with impending updates.

**Comment by stevenbird** [comment] 2015-06-09 23:36
@rleegoldman would you please see if you can reproduce this error with the current HEAD revision? https://github.com/nltk/nltk/archive/develop.zip

**Comment by rmalouf** [comment] 2016-04-11 04:58
This is still a problem (in Python 2.7).  The problem is in `_handle_lusubcorpus_elt()`, specifically:

```
            sc['name'] = str(elt.get('name'))
```

The type of `elt.get('name')` is either `str` or, if it contains a non-ASCII character, `unicode`, so the extra call to `str()` either is redundant or will fail.  A very simple solution is to just take out the call to `str()`, thusly:

```
            sc['name'] = elt.get('name')
```

Then `sc['name']` will also either be a `str` or a `unicode` object, as appropriate.  Would that cause any problems?  @wooters?

**Comment by nschneid** [comment] 2016-04-11 13:10
Apologies, I had fixed this with a bunch of other planned improvements that I never finished testing.

**Comment by wooters** [comment] 2016-04-12 15:53
Thanks @nschneid !

**Closed as completed** 2016-04-13 14:12 UTC
