### ISSUE TITLE
Error through training seq2seq model

### ISSUE THREAD

**Issue by somah1411** [nltk/nltk#1762] opened 2017-06-29 07:57 UTC
in test_batches
    bleu, bleu_log = data_util.corpus_bleu(all_B_predict, all_B_raw)
TypeError: 'int' object is not iterable

**Comment by alvations** [comment] 2017-06-29 09:13
@somah1411 Are you posting the issue to the correct repository? There's no seq2seq model in NLTK (at least not yet) =)

Could you further explain the problem so that we can help you better? 

 - Which seq2seq code outside of NLTK are you using?
 - Where is the `corpus_bleu` function coming from?
 - What is the input for `all_B_predict` and `all_B_raw`?

**Comment by somah1411** [comment] 2017-06-30 05:55
I use seq2seq model and Blue function from nltk, but the value is 0, also, what is the  mininum size foe the data that i have to use

Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by alvations** [comment] 2017-07-06 00:58
@somah1411 Could you further explain the problem so that we can help you better?

Which seq2seq code outside of NLTK are you using?
Where is the corpus_bleu function coming from?
What is the input for all_B_predict and all_B_raw?

----

Take a look at the examples in the docstring and see whether it helps you to understand how the BLEU score function should be used, see https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L104

**Comment by alvations** [comment] 2018-08-17 05:39
Closing `off-topic` issues to clean up the issue tracker. Please feel free to reopen or create PR the issue is really related to NLTK code.

**Closed as completed by alvations** 2018-08-17 05:39 UTC
Labels: Off-topic
