### ISSUE TITLE
Install with pip3 is broken (new release of setuptools?)

### ISSUE THREAD

**Issue by progval** [nltk/nltk#824] opened 2014-12-31 09:26 UTC
I use Travis CI to run builds every 12 hours; and one hour ago, the [install of nltk](https://travis-ci.org/ProjetPP/integration/builds/45504432#L708) on this environment broke:

```
Collecting nltk
Downloading nltk-3.0.0.tar.gz (962kB)
100% |################################| 966kB 6.6MB/s
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-k8c9g1/nltk/setup.py", line 37, in <module>
del sdist.finders[:]
AttributeError: 'module' object has no attribute 'finders'
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-k8c9g1/nltk/setup.py", line 37, in <module>
del sdist.finders[:]
AttributeError: 'module' object has no attribute 'finders'
```

**Comment by andresriancho** [comment] 2014-12-31 22:25
Confirmed, installation doesn't work anymore.

**Comment by andresriancho** [comment] 2014-12-31 22:30
This is the setuptools version that doesn't work:

```
# python -c 'import setuptools; print setuptools.__version__'
10.1
```

**Comment by andresriancho** [comment] 2014-12-31 22:33
Confirmed, the attribute doesn't exist in [the latest version](https://bitbucket.org/pypa/setuptools/src/41db17ef8356cebd6c7d04b91d82f745c4662360/setuptools/command/sdist.py?at=default)

**Comment by andresriancho** [comment] 2014-12-31 22:36
Looks like something similar to this would work, but need a maintainer to confirm:

```
from setuptools.command import sdist
sdist.walk_revctrl = lambda **kwargs: pass
```

**Comment by andresriancho** [comment] 2014-12-31 22:38
Or maybe just remove these lines?:

```
from setuptools.command import sdist
del sdist.finders[:]
```

**Comment by markuskiller** [comment] 2015-01-01 15:16
Temporary workaround for users who have `setuptools>=10.0` installed in their python environment:

```
pip install setuptools==9.1 
# this will automatically uninstall newer/older setuptools versions first

pip install -U nltk
```

To check for `setuptools` version, type `pip list`:

```
pip list
# result in clean virtual environment
pip (6.0.3)
setuptools (10.1)
```

**Comment by markuskiller** [comment] 2015-01-01 18:08
Workaround for `.travis.yml -->` add `setuptools` to `before_install` section:

```
...

before_install:
    - ...
    - "pip install setuptools==9.1"
...
```

Workaround for `.tox.ini -->` add `setuptools` to `deps` in `[testenv]` (adding it to `requirements.txt` won't do the trick, as the correct version of `setuptools` needs to be installed before `requirements.txt` is processed):

```
...

[testenv]
commands = ...
deps = 
    setuptools==9.1
    -rrequirements.txt
...
```

**Comment by andresriancho** [comment] 2015-01-02 02:20
@stevenbird ideas on a definitive fix?

**Comment by papachoco** [comment] 2015-01-03 00:02
Is there a time frame for a 3.0.1 release?
Carlos

**Comment by aliostad** [comment] 2015-01-04 13:11
So its not just me then.

**Comment by yacc143** [comment] 2015-01-05 16:40
Is it also possible to fix this for 2.0.4? We are currently not able to upgrade to NLTK3.

**Comment by the-efi** [comment] 2015-01-06 16:34
Another "Please fix this soon" vote from me.

**Comment by xuw10** [comment] 2015-01-06 20:10
It also happened to me when I was trying to install nltk on my mac by running:
sudo pip install -U nltk

**Comment by briandeheus** [comment] 2015-01-07 05:07
+1 for fixing this asap.

**Comment by intentionally-left-nil** [comment] 2015-01-09 08:40
+1 affected by this

**Comment by adepue** [comment] 2015-01-10 23:04
+1 for a fix for this

**Comment by stevenbird** [comment] 2015-01-12 00:54
I cherry-picked from #827 into [release-2.0.4](https://github.com/nltk/nltk/tree/release-2.0.4) and [release-3.0.0](https://github.com/nltk/nltk/tree/release-3.0.0) and updated the files at https://pypi.python.org/pypi/nltk/2.0.4 and https://pypi.python.org/pypi/nltk/3.0.0

**Closed as completed by stevenbird** 2015-01-12 00:54 UTC

**Comment by andresriancho** [comment] 2015-01-12 11:35
@stevenbird why not a +1 in the minor version number?

**Comment by stevenbird** [comment] 2015-01-12 11:41
There's no change in the codebase, and it seemed like overkill to trigger fresh downloads. However, I can do +1 if people think it's the right thing to do. Note that 3.0.1 should be out soon.

**Comment by andresriancho** [comment] 2015-01-12 11:48
Ok, thanks for clarifying

**Comment by kmike** [comment] 2015-01-12 11:58
+1 for point releases: replacing a released file could cause problems with mirrors, local caches, stale md5 sums. For example, if user already has nltk 2.0.4 in pip download cache then `pip install -U 'nltk < 3.0'` may not work because pip could think the cached version is the latest (I haven't tried it though).

**Comment by adepue** [comment] 2015-01-12 13:14
+1 on point releases as well.
We had to go through and clear pip caches everywhere to get this update.

**Comment by the-efi** [comment] 2015-01-12 15:44
+1 to get a new version. Without it it goes like this:

```
Collecting nltk<2.1,>=2.0 (from -r requirements.txt (line 53))
  Using cached nltk-2.0.4.tar.gz
  Hash of the package https://pypi.python.org/packages/source/n/nltk/nltk-2.0.4.tar.gz#md5=8d0d43575b8a4cedf9ee5e4440cd326d (from https://pypi.python.org/simple/nltk/) (b17aad070ae9a094538e4b481409db09) doesn't match the expected hash 8d0d43575b8a4cedf9ee5e4440cd326d!
  Bad md5 hash for package https://pypi.python.org/packages/source/n/nltk/nltk-2.0.4.tar.gz#md5=8d0d43575b8a4cedf9ee5e4440cd326d (from https://pypi.python.org/simple/nltk/)
```

**Comment by stevenbird** [comment] 2015-01-12 23:13
I've posted [2.0.5](https://pypi.python.org/pypi/nltk/2.0.5) and reinstated [2.0.4](https://pypi.python.org/pypi/nltk/2.0.4). I've created [3.0.1](https://pypi.python.org/pypi/nltk/3.0.1) which differs from 3.0.0 only in the fix to setup.py.

**Comment by kmike** [comment] 2015-01-13 09:09
Thanks @stevenbird!

**Comment by tsyber1an** [comment] 2015-03-14 00:04
@markuskiller thanks!
