### ISSUE TITLE
already downloaded 'wordnet' but can't find it

### ISSUE THREAD

**Issue by canfang-feng** [nltk/nltk#3028] opened 2022-07-28 12:26 UTC
Hello, I ran `nltk.download('wordnet')`  in jupternotebook in Linux.
```
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/xxxx_linux/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
```
then then i ran 
```py
from nltk.stem.wordnet import WordNetLemmatizer
WordNetLemmatizer().lemmatize("better kip")
```
got error message
```
LookupError                               Traceback (most recent call last)
File ~/.cache/pypoetry/virtualenvs/disaster-response-pipeline-project-Ber-KOyS-py3.8/lib/python3.8/site-packages/nltk/corpus/util.py:80, in LazyCorpusLoader.__load(self)
     79 except LookupError as e:
---> 80     try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
     81     except LookupError: raise e

File ~/.cache/pypoetry/virtualenvs/disaster-response-pipeline-project-Ber-KOyS-py3.8/lib/python3.8/site-packages/nltk/data.py:673, in find(resource_name, paths)
    672 resource_not_found = '\n%s\n%s\n%s\n' % (sep, msg, sep)
--> 673 raise LookupError(resource_not_found)

LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  Searched in:
    - '/home/xxxx_linux/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
...
    - '/usr/local/lib/nltk_data'
    - '/home/xxxx_linux/.cache/pypoetry/virtualenvs/disaster-response-pipeline-project-Ber-KOyS-py3.8/nltk_data'
    - '/home/xxxx_linux/.cache/pypoetry/virtualenvs/disaster-response-pipeline-project-Ber-KOyS-py3.8/lib/nltk_data'
**********************************************************************
```

in the terminal, i also try to ` cd /home/xxxx_linux/nltk_data`, i only found two folders `corpora  tokenizers`

Anyone know what is the reason to cause it? I assumed it should download successfully, but it is not there.

**Comment by jjmalina** [comment] 2022-08-03 16:08
I'm having the same exact issue. `nltk.download('wordnet')` does get run and the data is there in my docker container:

```
root@51c3093cc712:/code# ls -la /root/nltk_data/corpora/wordnet.zip 
-rw-r--r-- 1 ubuntu ubuntu 10775600 Aug  1 20:26 /root/nltk_data/corpora/wordnet.zip
```

**Comment by canfang-feng** [comment] 2022-08-03 16:14
For some reason, the process couldn't unzip it by itself. I fixed it by manually unzipping the "wordnet.zip" file.

**Comment by jjmalina** [comment] 2022-08-03 17:24
@canfang-feng thanks!

my workaround was to download the wordnet data outside of python:

```
python3 -m nltk.downloader wordnet
unzip /root/nltk_data/corpora/wordnet.zip -d /root/nltk_data/corpora/
```

**Comment by tomaarsen** [comment] 2022-09-02 05:26
I'll close this now that you've got it working!

**Closed as completed by tomaarsen** 2022-09-02 05:26 UTC

**Comment by aabbi** [comment] 2022-11-02 14:12
Running into this too
could something maybe wrong with the packages index ?
In this commit, https://github.com/nltk/nltk_data/commit/6c753e81dfcea267c8c35e7f30e638587830f2bb - the value of unzip was changed from 1 to 0 for "wordnet" package

**Comment by tomaarsen** [comment] 2022-11-02 14:20
@aabbi Another relevant commit: https://github.com/nltk/nltk_data/commit/fa6c72c1586653f5885a6df7790799711077f1d1
The commit you linked is simply an auto-build of the data elsewhere in the repository. This commit above is where the unzip value was changed. It was changed based on the recommendation of this issue: https://github.com/nltk/nltk_data/issues/187.

@ekaf Do you know if this could have caused issues here? (Sorry for the ping!)

**Comment by ekaf** [comment] 2022-11-02 17:48
The _wordnet_ library in NLTK 3.7 doesn't handle zipped files properly. The problem has been fixed for a while in the _develop_ branch on Github. So  using the latest  _wordnet.py_ module from Github (https://raw.githubusercontent.com/nltk/nltk/develop/nltk/corpus/reader/wordnet.py) should fix the problem.

However, until this is released in a stable version, the easiest workaround is to unzip the wordnet.zip data package manually, as mentioned by @canfang-feng (https://github.com/nltk/nltk/issues/3028#issuecomment-1204172813).

**Comment by tomaarsen** [comment] 2022-11-02 18:09
Wonderful! I should have remembered. I believe we should have another release out soon.

**Comment by aabbi** [comment] 2022-11-02 19:21
ok, thanks for the info and the quick replies. 
For now, I downgraded to 3.6.5 where it seems to be working ok

**Comment by armanexplorer** [comment] 2022-11-10 18:48
> For some reason, the process couldn't unzip it by itself. I fixed it by manually unzipping the "wordnet.zip" file.

As a complementary,

You can find the path to this zip file using `nltk.find` like this:
```python
import nltk
print(nltk.find('corpora/wordnet.zip'))
```
---
In my case (Windows 10 + NLTK 3.7), the full path of `wordnet.zip` was:

`C:\Users\arman\AppData\Roaming\nltk_data\corpora\wordnet.zip`

I extracted this zip file in its directory (`corpora`), which created the `wordnet` directory there. After that, the problem was resolved!

_NOTE_: It is assumed you downloaded `wordnet.zip` by running `nltk.download('wordnet')` or manually, and the file is located in the nltk paths.

**Comment by ksteflovic** [comment] 2023-07-13 10:11
> > For some reason, the process couldn't unzip it by itself. I fixed it by manually unzipping the "wordnet.zip" file.
> 
> As a complementary,
> 
> You can find the path to this zip file using `nltk.find` like this:
> 
> ```python
> import nltk
> print(nltk.find('corpora/wordnet.zip'))
> ```
> 
> In my case (Windows 10 + NLTK 3.7), the full path of `wordnet.zip` was:
> 
> `C:\Users\arman\AppData\Roaming\nltk_data\corpora\wordnet.zip`
> 
> I extracted this zip file in its directory (`corpora`), which created the `wordnet` directory there. After that, the problem was resolved!
> 
> _NOTE_: It is assumed you downloaded `wordnet.zip` by running `nltk.download('wordnet')` or manually, and the file is located in the nltk paths.

This was helpful. Thank you very much!

**Comment by tuky** [comment] 2023-09-01 08:12
still not properly unzipped in `3.8.1` :confused:

**Comment by lordsoffallen** [comment] 2024-01-08 10:40
Still having the same issue..

**Comment by thangabalaji1** [comment] 2024-07-15 16:11
The problem is not resolved . Please reopen the issue

**Comment by darshit001** [comment] 2024-08-02 05:47
i also get this same error

**Comment by youssef-khalf** [comment] 2024-08-12 15:39
try this  code 👍 
import nltk
import zipfile
import os

# Path to the zip file and extraction directory
zip_file_path = '/kaggle/working/nltk_data/corpora/wordnet.zip'
extract_to_path = '/kaggle/working/nltk_data/corpora/'

# Unzip the WordNet data
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to_path)

# Set the NLTK data path to the directory containing the extracted files
nltk.data.path.append('/kaggle/working/nltk_data/')

# Function to convert POS tags to WordNet format
from nltk.corpus import wordnet

**Comment by amanmibra** [comment] 2024-08-18 14:48
Getting this error

**Comment by 123walid** [comment] 2024-08-19 01:30
still getting this error:
I changed the nltk version I unzipped the zip file and the same error:
<img width="527" alt="errord" src="https://github.com/user-attachments/assets/d6c52290-b1b1-445e-8fd6-87a4601fed34">

**Comment by ashwin2509** [comment] 2025-03-13 22:16
The problem is not resolved . Please reopen the issue

**Comment by SBoone2017** [comment] 2025-08-26 14:31
The issue persists.
