### ISSUE TITLE
ModuleNotFoundError: No module named 'regex._regex'

### ISSUE THREAD

**Issue by 7oda111** [nltk/nltk#2870] opened 2021-10-27 12:23 UTC
i use this code in order to build a pipeline 
---------------
import re
import nltk 
from textblob import TextBlob 
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from textblob import Word 
from nltk.util import ngrams
import re
from wordcloud import WorldCloud , STOPWORDS 
from nltk.tokenize import word_tokenize 
-----
the the error  ModuleNotFoundError: No module named 'regex._regex' come up 
any suggestions on the reason ???

**Comment by tomaarsen** [comment] 2021-10-27 12:26
@7oda111  I would recommend running
```
pip install -U regex
```
in a terminal. I suspect your version of `regex` is outdated.

**Comment by tomaarsen** [comment] 2021-11-21 11:17
I'm closing this. I suspect my comment above would work, and otherwise there are many other people who have encountered this before, e.g. https://github.com/psf/black/issues/1207, which resolve it by pinning regex to a specific version.

**Closed as completed by tomaarsen** 2021-11-21 11:17 UTC

**Comment by erikc96** [comment] 2022-03-30 01:09
Just had this issue popup. Does it make sense to pin the regex version to this project's requirements?

**Comment by tomaarsen** [comment] 2022-03-30 07:47
@erikc96 I'd say so. I'm willing to say that you won't have this issue again with `regex>=2021.8.3`. Good luck!

**Comment by Shivam-3108** [comment] 2023-05-29 12:32
this issue popped up when I was importing nltk from a layer in aws lambda, the issue is with lambda detecting .cpython-xxxxx.so type of extensions and its compatibility

**Comment by Firstoff** [comment] 2024-11-07 19:38
python-3.10.11-amd64 need - 
![Screenshot 2024-11-07 223753](https://github.com/user-attachments/assets/40dcfcfd-c269-472e-97e7-b264d82e173f)
![Screenshot 2024-11-07 223827](https://github.com/user-attachments/assets/77489f17-06a5-4a70-9ef6-d34a77964aef)
растудыть её тудыть.
